### ISSUE TITLE
IDresolver: In yeastmine, semicolon is a valid separator and comma isn't

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#102]
solution: probably per-mine separator config with sane defaults.

**Comment by yochannah** [comment]
tell @kkarra

**Comment by julie-sullivan** [comment]
https://github.com/intermine/intermine/blob/dev/intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties#L35
Those are the defaults. Kalpana overrides that parameter in her local web.properties file. These values are available via the web services.

**Comment by yochannah** [comment]
This works.
