### ISSUE TITLE
Tooltip doesn't show for some left aligned items

### ISSUE THREAD

**Issue by nuin** [intermine/bluegenes#117]
Please check the screencap attached, tried on Safari 10.0.3 (12602.4.8)

<img width="418" alt="screen shot 2017-03-30 at 9 27 02 am" src="https://cloud.githubusercontent.com/assets/6273/24515154/8f5277dc-152b-11e7-83c4-18aa275d9d99.png">

**Comment by yochannah** [comment]
@nuin could you test this in http://bluegenes.apps.intermine.org/ for us? I think it's probably been fixed.
