### ISSUE TITLE
Quicksearch: add facets and counts

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#119]
Gramene does this really nicely: 

![image](https://cloud.githubusercontent.com/assets/9271438/24530290/ce5d3e3c-1565-11e7-8cbe-3f057a96d5c0.png)

**Comment by yochannah** [comment]
Still needed

**Comment by heralden** [comment]
This is done on the search page, but not on the typeahead search (where it would probably be too busy to display).
