### ISSUE TITLE
Region search: Search options superimpose results in Safari [css / less issue]

### ISSUE THREAD

**Issue by nuin** [intermine/bluegenes#121]
Please check the attached screen cap, on Safari 10.0.3 (12602.4.8). After a region search the options stay on the screen and the element is on top of the search results.

<img width="1196" alt="screen shot 2017-03-31 at 10 02 45 am" src="https://cloud.githubusercontent.com/assets/6273/24560962/c41b465a-15f9-11e7-98fc-e96680f9bd74.png">

**Comment by nuin** [comment]
Has this been fixed?

**Comment by yochannah** [comment]
I've added "help wanted" so a potential GSoC can pick this up if they wish. 

- Please test this in Safari and either comment that it is fixed, or modify https://github.com/intermine/bluegenes/blob/dev/less/components/regions.less to resolve the issue.
- Favour small changes over redesigning the whole page. 
- hopefully no HTML / hiccup changes are needed, but if they are, this is the file with the view for this page: https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/sections/regions/views.cljs

**Comment by nuin** [comment]
I am assuming this is fixed, after a year of the last update.
