### ISSUE TITLE
Ability to create a list from the genes found in a search

### ISSUE THREAD

**Issue by dmgood11** [intermine/bluegenes#132]
Search produces results that can be facetted by clicking on a category (e.g., "Gene", "ProteinDomain").  It would be very useful if, after clicking on the "Gene" category, one could select several or all the gene results and use them to create a list.

**Comment by yochannah** [comment]
This PR should address the issue bye allowing user to check results then move to the list results page to view and/or save the checked results https://github.com/intermine/redgenes/pull/135

**Comment by yochannah** [comment]
#135 has now been merged.
