### ISSUE TITLE
Label report page references/collections by ref/coll name rather than class name

### ISSUE THREAD

**Issue by sammyjava** [intermine/bluegenes#134]
In lieu of a naming configuration a la webconfig.xml, it would be good if the collections and references (another issue) use the collection or reference name rather than the class name of the referenced object(s). In the attached example, rather than "Gene" the genes collection should be "Spanned Genes" from QTL.spannedGenes, "Linkage Group Range" should, technically, be "Linkage Group Ranges" from QTL.linkageGroupRanges, and "Genetic Marker" should be "Associated Genetic Markers" from QTL.associatedGeneticMarkers. Let me know if there's a way of doing this already!
![2017-05-16-160106_1680x1026_scrot](https://cloud.githubusercontent.com/assets/5657219/26130377/a419fb2c-3a51-11e7-8731-8d8faadeac6e.png)

**Comment by yochannah** [comment]
@sammyjava Julie was on the case for us about this one - InterMines 1.7.3 and greater will have this attribute available in the model: https://github.com/intermine/intermine/issues/1410 It shouldn't be too hard to add to BlueGenes :)

**Comment by heralden** [comment]
I think this has been fixed a while ago. `displayName` is present and being used for the headers.

Please re-open if I have misinterpreted!

![](https://media.discordapp.net/attachments/585112120350212103/631812757112487936/2019-10-10-121755_757x885_scrot.png)
