### ISSUE TITLE
Results count different

### ISSUE THREAD

**Issue by kkarra** [intermine/bluegenes#143]
For YeastMine, FeatureType-->Genes shows 5911 rows in bluegenes vs 5915 rows in the mine.

**Comment by joshkh** [comment]
Thanks, @kkarra. There's a fix in the intermine/im-tables-3:dev branch that will be merged into master during the next release:

https://github.com/intermine/im-tables-3/blob/dev/src/im_tables/views/dashboard/main.cljs#L38
