### ISSUE TITLE
Query infrastructure: add all queries to a "recent queries" section in app db

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#149]
Add all queries to a "recent queries" section in app db. Ensure that all pages use it where possible rather than custom results areas (e.g. list upload, enrichment, list results page).

This would allow us to track recent queries effectively in the mymine page, and restore old states quite easily - e.g. on pressing the back button. 

Probably something like 
```
:queries [ 
              {:query <SOME QUERY, probably paginated to 20 results> 
                :results <THE RESULTS> 
                :ran-by "results-page" 
                :preview? false}
               {:query <SOME QUERY, limited to 5 results> 
                :results <THE RESULTS> 
                :ran-by "templates" 
                :preview? true} ]
```

@joshkh does this sound right? Anything to add? I think storing them in a map is less useful than an ordered collection.

**Comment by joshkh** [comment]
Looks good!

An ordered collection definitely has its advantages but it makes it hard to look up previous queries by name (I ran into this problem with the prior workflow functionality in bluegenes). What do you think about a sorted-map keyed on a `:timestamp`?

**Comment by yochannah** [comment]
Like this, with assumptions queries is sorted (the timestamp being seconds since epoch)? sounds good!

```:queries {
         :01543543543
              {:query <SOME QUERY, probably paginated to 20 results> 
                :results <THE RESULTS> 
                :ran-by "results-page" 
                :query-id :01543543543
                :preview? false}
         :01543543542
               {:query <SOME QUERY, limited to 5 results> 
                :results <THE RESULTS> 
                :query-id :01543543542
                :ran-by "templates" 
                :preview? true} ```

**Comment by yochannah** [comment]
@joshkh Am I right in thinking that https://github.com/intermine/bluegenes/pull/223 addresses this issue?

**Comment by yochannah** [comment]
It looks like in `:results :history` in app db we have recent queries.
