### ISSUE TITLE
Review README and ensure BlueGenes setup documentation is up to date

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#154]
Review this doc: 

https://github.com/intermine/bluegenes/blob/dev/README.md

This task requires: 

1. Set up BlueGenes, following the readme link above.
2. If you get stuck at any point, figure out why and update the readme so it's clearer, or report a [bug](https://github.com/intermine/bluegenes/issues) if it's something that can't be worked around. 
3. When you're done, report your findings on the ticket and PR your readme changes / additions. Edits need to be more than just README formatting to be eligible. 
4. Bask in glory.

When you get stuck, StackOverflow and Google are good options. Alternatively pop into the [InterMine chat](http://chat.intermine.org) or ping @yochannah or @joshkh for help. 

No clojure/script experience necessary, but it may be helpful!

**Comment by yochannah** [comment]
If you complete this task, you may wish to follow up with https://github.com/intermine/bluegenes/issues/77

**Comment by cristianossd** [comment]
It sounds very interesting. I'll configure the environment and work on this, @yochannah

**Comment by yochannah** [comment]
@cristianossd did you ever get the chance to review this? if not, no worries - just reviewing issues and I may close this one.

**Comment by cristianossd** [comment]
No, @yochannah, I don't scheduled yet
