### ISSUE TITLE
SVG: Create an icon for list unions. 

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#157]
The icon needs to be the same as this:
![image](https://user-images.githubusercontent.com/9271438/31278880-abd5310c-aa9e-11e7-8f5e-6ce610ca0ec3.png)
(can also be viewed here: http://bluegenes.apps.intermine.org/#/debug) **but** without the top circle having a line all the way around, cutting the middle off - just one large empty space, like a figure eight that doesn't meet in the middle.

The code for the current list union / combine icon is here: https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/components/icons.cljs#L39 - this is in hiccup, rather than html, but can be translated to html easily http://htmltohiccup.herokuapp.com/

**Comment by harleo** [comment]
Can do but haven't used Hiccup yet, how do you exactly convert the SVG to your desired format?

**Comment by yochannah** [comment]
@harleo 

so this is the current icon in hiccup: 

```
[:symbol#icon-venn-combine
     {:viewBox "-5 0 160 100"}
     [:title "Combine these lists"]

     [:circle.venn-full
      {:r 50 :cx 50 :cy 50 :stroke-width 5 :fill "rgb(170,170,170)" :stroke "black"}]
     [:circle.venn-full
      {:r 50 :cx 100 :cy 50 :stroke-width 5 :fill "rgb(170,170,170)" :stroke "black"}]]
```

hiccup always eventually renders in the browser as html (there's a clojure compile step, but you don't have to worry about that), like so:

```
<svg viewBox="-5 0 160 100" id="icon-venn-combine" width="100%" height="100%"><title>Combine these lists</title><circle r="50" cx="50" cy="50" stroke-width="5" fill="rgb(170,170,170)" stroke="black" class="venn-full"></circle><circle r="50" cx="100" cy="50" stroke-width="5" fill="rgb(170,170,170)" stroke="black" class="venn-full"></circle></svg>
```

you can paste the html back into the html-to-hiccup converter to turn it into hiccup. 

Does that help?

**Comment by harleo** [comment]
@yochannah Thanks, just got it figured out. Should be up for PR in a second.

**Comment by harleo** [comment]
Hope this helps and works.
#158
