### ISSUE TITLE
SVG: Create exclusive disjunction icon

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#159]
Example of the icon style we need: https://simple.wikipedia.org/wiki/Exclusive_disjunction 

See https://github.com/intermine/bluegenes/issues/157 for the basic requirements - this is creating a new icon based on an existing venn diagram icon set, that conveys the "disjunction: diagram as shown in the wikipedia article above. 

This is a visual of the icons:
![image](https://user-images.githubusercontent.com/9271438/31282957-0552ad60-aaac-11e7-9143-d526b91a861c.png)

Example code for the other icons is here: 
The code for the current list union / combine icon is here: https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/components/icons.cljs#L39-L65 -  this is in hiccup, rather than html, but can be translated to html easily http://htmltohiccup.herokuapp.com/

**Comment by harleo** [comment]
Working on it.

**Comment by harleo** [comment]
@yochannah 
Done. #160

**Comment by yochannah** [comment]
fixed by #160
