### ISSUE TITLE
SVG+hiccup: Replace homepage questionmark icon with more sans-serif style questionmark

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#162]
**Picking this issue up:**
1. Read through and make sure you understand the task (it's ok to ask questions if needed)
2. Leave a comment on the issue saying you intend to work in it

**specs:**

See the blue questionmark here: [http://bluegenes.apps.intermine.org/](http://bluegenes.apps.intermine.org/).

![image](https://user-images.githubusercontent.com/9271438/31763135-48eb3b9c-b4b5-11e7-9748-8e5830ce4d0c.png)

It doesn't seem to really fit with the other two icons - we need to replace with an icon that looks a bit more in keeping with the theme.

The icon is located here: https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/components/icons.cljs#L332 this is in hiccup, rather than html, but can be translated to html easily http://htmltohiccup.herokuapp.com/

see https://github.com/intermine/bluegenes/issues/157 for a related ticket discussing converting html to hiccup and back

**Comment by artiemq** [comment]
I will work on this.
