### ISSUE TITLE
Make intermine.org readable on mobile

### ISSUE THREAD

**Issue by wbazant** [intermine/bluegenes#167]
I had a look at intermine.org on my phone (samsung galaxy ie random smartphone). The data doesnt fit on display because I think the page has hardcoded min width. Some text was outside the screen and there was no way to scroll to it.

**Comment by yochannah** [comment]
@wbazant I've had a look and I can see what you mean :( thanks for the feedback - that shouldn't be happening!

**Comment by yochannah** [comment]
FYI - I'm closing this issue just so I can move it to the main repo for intermine.org - it's still open for now here: https://github.com/intermine/intermine.github.io/issues/1
