### ISSUE TITLE
Handle old portal link

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#168]
Portal links shouldn't break when we retire the old ui. We need to make sure they still do.

http://intermine.readthedocs.io/en/latest/webapp/linking-in

Possible ways to do this: 

1. forward portal links to whatever new deep link address we create
2. have bluegenes be able to understand and parse portal links...

**Comment by heralden** [comment]
While it is important, it's not urgent, so we will leave this for later.

**Comment by danielabutano** [comment]
see https://github.com/intermine/bluegenes/issues/735
@uosl I think we can close it as duplicated
