### ISSUE TITLE
Warn when performing list operation on different types and handle errors

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#178]
At the moment on the My Data / Lists page, there are no type checks on allowing users to combine lists of different types, e.g. mixing a list of Genes with Proteins. It will just silently fail.

**Comment by julie-sullivan** [comment]
It should not fail at all. You can merge protein and gene lists in the current webapp. 

Is this the fault of the web service or bluegenes?

**Comment by heralden** [comment]
After speaking with Rachel, I have renamed this issue to what we want to achieve: It should be possible to perform list operations on lists of different types, but there should be a warning worded in the vein of "do you really want to do this," advising you to convert one of the lists first, as they are of differing types.

~~It also seems like we don't handle errors (which can happen in some cases, like when combining a list of organisms and genes, which don't have a common ancestor data type). We'll need to make sure these are displayed in a toast message.~~ Update: Errors are now shown in the new lists page.
