### ISSUE TITLE
My data: Drag & drop doesn't work in Firefox [clojurescript + js skills required]

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#185]
## Steps to reproduce: 

1. Visit  http://bluegenes.apps.intermine.org/#/mymine
2. log in using the test user "demo@intermine.org" with password "demo".
3. try to drag an item from "all items" onto a tag (on the left). This works in Chrome but not FF (extra points if someone can test this in Edge for us!) 

![image](https://user-images.githubusercontent.com/9271438/33281671-e63012ea-d39d-11e7-89a7-8bdfc680daeb.png)

### If you would like to pick this issue up, please do the following: 

1. Comment on the issue to let us know you're working on it! 
2. Follow the [readme](https://github.com/intermine/bluegenes/blob/dev/README.md) and get BlueGenes running on your system. (It's fine to ask for help if any of the steps aren't clear enough). 
4. Look at the mymine directory: https://github.com/intermine/bluegenes/tree/dev/src/cljs/bluegenes/sections/mymine/views and mymine.cljs in the views events and subs folders. to try and fix the issue.  
5. When you think you've fixed something, make a PR and we'll review it!

**Comment by XiangpengHao** [comment]
The sidebar not shown on the dev branch so I cannot reproduce the bug. Based on my observation from the developer tools, the problem is probably in FF we need to explicitly set a listener `ondragstart` and call `event.datatransfer.setdata(...)` in it. I tried this from the console and it works.
BTW, it works in Edge.

**Comment by yochannah** [comment]
You are right! We actually decided to take out the tags on the left a few days ago. We should have closed this ticket at the time, sorry! I'm going to close it now, but we will need to re-open the ticket when we bring tags back to life so your investigation has still been incredibly helpful. 

Also, it's good to hear it works in Edge - that's the one browser we don't have easy access to in the team as we have no windows machines!

**Comment by yochannah** [comment]
(Expanding on this - we need to re-engineer the back-end of the tags infrastructure. It's storing the tags in the bluegenes postgres db but it would be better off using InterMine's native tagging via the api instead). We'll bring tags back once we've done that.
