### ISSUE TITLE
My data: List subtraction: consider making possible actions clearer

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#186]
Currently the subtraction list page looks like this:
![image](https://user-images.githubusercontent.com/9271438/33282256-0a8c283e-d3a0-11e7-92f6-71c3714be7fc.png)

Test users have reported that subtraction doesn't work. This isn't quite correct, but it can error out silently and make it seem like it's not working. We need to make it easier if possible.

One user test session, we observed the user immediately typed a name and clicked save. Nothing saved (hence the 'empty' bit in the screenshot). This is expected behaviour in this scenario.

**possible improvement:**

- [x] Consider automatically trying to position it such that the default action is "subtract the larger list from the smaller list", and put the little switcher button more prominent on a raised button. 

- [ ] Also, maybe pre-run the operation and return the expected count - if the count is 0, warn or error before the user performs it! 

- [ ] ~Consider adding drag and drop as well (not only drag and drop, though) to match the tag behaviour~ (⬅️ edit: this bullet point refers to a part of the interface that no longer exists, please ignore).

**Comment by yochannah** [comment]
maybe that same page could begin its life a bit more like this? (note no "empty" by default. my mock is missing the buttons to move the lists from the top to the bottom, too.) ![20171127_183001](https://user-images.githubusercontent.com/9271438/33282726-6b91a7ca-d3a1-11e7-839a-ded2d6f250f3.jpg)

**Comment by roshnidesigns** [comment]
>  Consider adding drag and drop as well (not only drag and drop, though) to match the tag behaviour

Can you elaborate this? I mean the use, you suggest drag drop used for what? Quite unclear to me😅

**Comment by yochannah** [comment]
I think that that comment about drag and drop has aged away and refers to an interface that no longer exists 😓 please ignore that bit!
