### ISSUE TITLE
Superuser accounts needed!

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#194]
If there are options to enable, disable, and install tools on report pages, we'll need to make sure this is restricted to administrators only.

**Possible implementation method:** no default admin user enabled, but if you create one by adding a text file on the server, it is generated for you and added to the db, similar to tomcat's default: https://tomcat.apache.org/tomcat-8.0-doc/manager-howto.html#Configuring_Manager_Application_Access

**Comment by julie-sullivan** [comment]
http://iodocs.apps.intermine.org/flymine/docs#/ws-whoami/GET/user/whoami -- we could add a boolean `superuser` to that web service.

Would that be sufficient?

**Comment by yochannah** [comment]
I naively think that would help us present a tool api appropriately. 

There might be other things to worry about though -  is everything a superuser can do is also accessible via the api? Somethings I'm sure will be fine - some of the list management stuff is via tags, right? But what about things like list upgrade? I haven't spent much time using the jsp pages as superuser so I'm not sure what the full set of things they do is.

**Comment by heralden** [comment]
The tool usecase outlined in the first post has been solved with the addition of the `superuser` boolean to `whoami` endpoint.
