### ISSUE TITLE
Templates: Add a "view" button [clojurescript]

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#197]
### Problem: 
Sometimes it's not obvious what to do with a template. See the screenshot below - it's actually possible to click on all the white sections (e.g. Affymetric probset --> Gene, Protein Domain --> Protein + Genes, so on). 

![image](https://user-images.githubusercontent.com/9271438/33887677-798aff46-df42-11e7-96f9-674ca49be212.png)

### To fix this: 
I'd suggest we do two small items:

- [ ] change the cursor to a pointer when hovering over the sections
- [ ] add a button to each section. Perhaps the text would be something like `View >>`

### If you would like to pick the issue up:

If you would like to pick this issue up, please do the following: 

1. Comment on the issue to let us know you're working on it! 
2. You can try out a working demo here, and make sure you know how to replicate the issue: http://bluegenes.apps.intermine.org/ - go to ‘templates’ (along tabs at top). 
3. Follow the [readme](https://github.com/intermine/bluegenes/blob/dev/README.md) and get BlueGenes running on your system. (It's fine to ask for help if any of the steps aren't clear enough). 
4. Look at the template view file and decide where to add the button: https://github.com/intermine/bluegenes/tree/dev/src/cljs/bluegenes/components/templates 
5. When you think you've fixed it, make a PR and we'll review it! It's better to make small pulls that fix one or two issues than a single mega pull. 

What to do if you need help at any point: Comment on this issue to ask for help, mention @yochannah (that's me!), email me (my email address is in my profile), or tweet yoyehudi on twitter.

**Comment by triqp** [comment]
@yochannah I'm interested in picking this up if that is alright with you!

**Comment by yochannah** [comment]
@tphorbin Brilliant! Poke me if you get stuck or have any questions :)

**Comment by yochannah** [comment]
resolved by #204
