### ISSUE TITLE
My Data + API: List operations throws a 500 POST error in console

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#201]
Steps to reproduce (withdev console open):

1. select two lists on the my data page
2. click "combine" at top of window
3. Note the POST error: `POST http://localhost:5000/api/mymine/entries 500 (Server Error)`
![image](https://user-images.githubusercontent.com/9271438/33996408-06e55e3a-e0d9-11e7-9f7a-220cd3ee85d8.png)

**Comment by yochannah** [comment]
Worth mentioning, the list combination operation DOES work.

**Comment by yochannah** [comment]
Note: this actually happens when logged out, and with other list ops as well.

**Comment by heralden** [comment]
Couldn't reproduce. Seems like it has been fixed in an intermine release.
