### ISSUE TITLE
Kill anon tokens

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#21]
If we cache authentication tokens (which we do) and we get a 401 for an anonymous token - I think this happens when a token expires due to a rebuild or a certain timeout, we need to automatically delete the token and try again. Or maybe @joshkh had some session ideas about how to handle this?

**Comment by yochannah** [comment]
**To test this:** 

1. Change the `:token` key for your active mine in localstorage to something wrong, perhaps "FAKETOKEN". 
 2. reload redgenes with the console open. 
 3. There should be no 401s in the console, and you should have a new token in place of your old token. If the bug isn't fixed you'll see the token set to `null` instead.

**Comment by yochannah** [comment]
Wait, this is only half fixed. If a mine redeploys tokens will die, but the boot method won't happen again. How do we handle this scenario? *any* communication method could be a problem here.

**Comment by yochannah** [comment]
After a brief discussion with @joshkh - we probably need to add an on-failure to im-operation, and ensure that all communication uses im-operation. 

The on-failure function should probably try renewing the authentication token and pop up a toast saying something like "There's been a communication error. Please try again. If this persists, please contact support" with a link that guides them through a cache clear and localstorage clear before contacting us... 

This is out of scope for the end-of-march  workshop target.

**Comment by joshkh** [comment]
See PR #115 

This behaviour will change when we introduce log-in capabilities. For now we show a warning message to the user when a token is invalid and present the option to refresh the application.

**Comment by joshkh** [comment]
![image](https://cloud.githubusercontent.com/assets/4752532/23959521/53242146-099d-11e7-8e6c-e237aabd8fbd.png)
