### ISSUE TITLE
Blue genes - needs to work for local dev webapps.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/bluegenes#211]
We are working on getting a blue gene target. This will be great to point to beta.flymine.org etc. However, we also need it to work for local instances. People need to use blue genes with their own local data.

I understand this information is in a properties file (with a lot of other information), in the JAR.

Instead, can this information be in the config.edn file provided to the JAR. Default values can be retrieved from the web services.

This is needed for the InterMine 2.0 release.

Later we can set up a UI to edit this config in the blue genes app itself.

**Comment by julie-sullivan** [comment]
https://github.com/intermine/bluegenes/tree/dev/config/dev

1. set to be Java properties instead of edn file
2. Users can put the needed variables in their `flymine.properties` file. I can update gradle to write these properties to `config.edn` (or whatever the new name is) and pass that in.

**Comment by julie-sullivan** [comment]
https://github.com/intermine/bluegenes/blob/dev/src/cljc/bluegenes/mines.cljc
This is the config for all mines. 

How can I add my local FooMine so that blue genes can use it? I can't edit the file in the JAR!

**Comment by julie-sullivan** [comment]
Sort of a duplicate of #196

**Comment by julie-sullivan** [comment]
This is the current gradle target which works great! Blue genes starts up:

https://github.com/intermine/intermine/blob/gradle/intermine/webapp/build.gradle#L66

**Comment by julie-sullivan** [comment]
FYI everything in https://github.com/intermine/bluegenes/blob/dev/src/cljc/bluegenes/mines.cljc is already in the mine properties file.

**Comment by julie-sullivan** [comment]
Other notes:

* one beautiful day this file will be replaced / complemented by an admin interface
* don't want to make people edit JSON. java property files are best.
* user friendly! Sensible defaults, etc
* need docs, e.g. [web.properties](http://intermine.readthedocs.io/en/latest/webapp/properties/web-properties/)

**Comment by julie-sullivan** [comment]
```
Users can put the needed variables in their flymine.properties file. I can update
gradle to write these properties to config.edn (or whatever the new name is)
and pass that in.
```

I can also read each property and set as ENV variable.

**Comment by yochannah** [comment]
That might be a good idea, actually! it would make it easier to tell whether or not the bluegenes is standalone or inside an intermine. 

could we do something like this? 

`bluegenes-default-service-root="http://www.someintermine.org/someintermine"`

using dots or underscores as separators is fine too if that's easier, e.g. `bluegenes.default.etc` - it'll all end up the same when our config library interprets it

**Comment by julie-sullivan** [comment]
Historically Java properties use dots to separate phrases and dashes to seperate words. So `bluegenes.default-service-root`.

**Comment by julie-sullivan** [comment]
https://github.com/intermine/bluegenes/blame/dev/config/dev/README.md#L26
We only need the URL and mine name.

**Comment by yochannah** [comment]
closing this issue for now - it's implemented and doubtless has bugs but we can open new tickets for those
