### ISSUE TITLE
List Results: breadcrumbs are added to the old trail even when you start a new set of actions

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#217]
Steps to reproduce:

1) create a list from the upload identifiers page.
2) go create a different list, unrelated to the first 
3) the breadcrumbs will make it look like each of these actions is a direct child action of the next rather than separate actions. (Maybe this is our intent?)

See screenshot below - each of the actions shown in the breadcrumb trail is separate! 

![image](https://user-images.githubusercontent.com/9271438/35973061-ef251faa-0ccb-11e8-9b14-b424cf6806c8.png)

**Comment by joshkh** [comment]
This should be fixed by the use-new-imtables PR

**Comment by yochannah** [comment]
It was!!
