### ISSUE TITLE
List results page is being inconsistent

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#218]
Reported by @kkarra: 

The list you think you see may not be the list it thinks it is. See screenshot below: 

- the enrichment you see is definitely not for the list of 1 items
- the save list button says there are 0 items in the list. (This may be an imtables thing)

![image](https://user-images.githubusercontent.com/9271438/35984659-d2a64518-0cec-11e8-954e-e30b89dfc433.png)

**Comment by yochannah** [comment]
Strong suspicion: This may be to do with slow-loading results returning and being associated with the wrong, newer query.

**Comment by yochannah** [comment]
This is _definitely_ due to slower network connections - which is why it's always worked fine for us, with beta flymine being in the same building :confounded:, but also why it was easy for Kalpana to notice give she's further away so won't get snappy speeds like we do... 

To reproduce: 
1. set network throttling in chrome (the slow 3g setting definitely works, but I think fast 3g will too and might be less agonizing): https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions
2. Make multiple visits to the list results page with different lists and watch the weirdness happen.

**Comment by joshkh** [comment]
Great detective work. I'll make sure that pending query requests are cancelled when a new one is made.

**Comment by yochannah** [comment]
Fixed by https://github.com/intermine/bluegenes/pull/226
