### ISSUE TITLE
Cursor doesn't change to hand when hover over a result item in Templates

### ISSUE THREAD

**Issue by amand1996** [intermine/bluegenes#224]
On the Bluegenes' Templates Page, the cursor should change to pointer when we hover over a result item.
![screenshot from 2018-02-27 15-40-11](https://user-images.githubusercontent.com/9645180/36722992-12cbdf08-1bd5-11e8-8de9-16c2962131e2.png)

**Comment by yochannah** [comment]
Hey Aman! Thanks for noticing and logging the issue! This actually has a fixed that hopefully will be merged into master soon and is live in dev - https://github.com/intermine/bluegenes/issues/197
