### ISSUE TITLE
Filters don't work on Bluegenes Template page when the result item is clicked

### ISSUE THREAD

**Issue by amand1996** [intermine/bluegenes#225]
There is a drop down filter (or rather say query generator) on the Bluegenes Templates page when some item is selected. It is not working. 
![screenshot from 2018-02-27 15-46-09](https://user-images.githubusercontent.com/9645180/36723264-c7e294b8-1bd5-11e8-912e-a5dd4c85b24a.png)

**Comment by yochannah** [comment]
I think you're right, BUT it is fixed in teh dev branch as well :) Thanks for reporting it though! 

P.S. You can test the dev branch here - might be a better idea for now :) 

http://devbluegenes.apps.intermine.org
