### ISSUE TITLE
Region search: Validate input.

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#23]
Right now whatever we input into the box is submitted to the sever. When the input is invalid we don't get verbose or meaningful error messages back, so we should validate the regions clientside before submission.

Demonstrative example: 
![example region search input](https://cloud.githubusercontent.com/assets/9271438/21427460/b0624a50-c84c-11e6-9903-2566ed6f1a10.png)

The 'ss' appended to the end of the input in that screenshot results in a 500 from the server, and no results for any of the regions.

**Comment by sehgalvibhor** [comment]
@yochannah : My thoughts on this is to implement a regex for the 'region-input' to check the string format before dispatching a function to the server otherwise raise a validation alert. Thoughts?

Also, I am not sure about the regex for the input field. Can you help me with this?

**Comment by yochannah** [comment]
@sehgalvibhor That sounds like a good approach! 

@rachellyne regarding @sehgalvibhor's question above, is a formula along the lines of (some alphanumeric chars):(numeric characters)(`..` or `-`)(numeric characters) appropriate? 

p.s. let me know if I wasn't clear enough there.

**Comment by rachellyne** [comment]
That will catch any inappropriately formatted regions but will not catch regions that do not return results because, for example, they are out of range for the sequence - but maybe that's ok (These should become obvious from the results.) Also it won't catch anything with a wrong chromosome number?  eg Drosophila only has chromosomes 1-4, so 8:xxxx..xxx would still go though as correct?

**Comment by yochannah** [comment]
Thanks @rachellyne! out of range / chromosome number checks probably need to be made on the server I think. @julie-sullivan does that sound right? Or do we have the data for valid ranges available via web service somehow?

**Comment by yochannah** [comment]
@sehgalvibhor While we're thinking about that second question, I think it's safe to proceed with the formula (some alphanumeric chars):(numeric characters)(.. or -)(numeric characters) - is that enough for you to go on? 

Here's an example of a regex being used in bluegenes: https://github.com/intermine/bluegenes/blob/6d76ff268f091d4726679f6088d60a5ebc988025/src/clj/bluegenes/ws/ids.clj#L18 - or search for [other re-pattern uses](https://github.com/intermine/bluegenes/search?q=re-pattern&unscoped_q=re-pattern).

**Comment by sehgalvibhor** [comment]
@yochannah : Yes I'll try out on the formula you mentioned. Just to confirm these can be multi-line and tab-spaced right?

Also, is it better if we disable the button dynamically like currently being done for empty search strings etc or wait for the user to press the button?
