### ISSUE TITLE
Error handling: no InterMine webapp

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/bluegenes#234]
Can we have a fatal error if the associated InterMine webapp is not available.

People can now launch their own blue genes against their local InterMine webapp. It will be easy to forget you don't have a tomcat running but the UI for blue genes gives no indication that's what's wrong.

*I* would never be this silly of course!

**Comment by yochannah** [comment]
Not that you'd know by experience, of course, but what happens currently? Just stuff doesn't work randomly, I'm guessing?

**Comment by yochannah** [comment]
We've gone to a lot of work to make bluegenes mine agnostic, so if it's _not_ passed an InterMine param BlueGenes will still work. This is just for when a param is passed but the mine is dead / the param is typoed / etc, right?

**Comment by yochannah** [comment]
Probably should be addressed at the same time as #235

**Comment by yochannah** [comment]
Copy/pasting from duplicate issue #403: 

Also, transcribing from @AdrianBZG in chat, he had the baseUrl as localhost, which caused errors.

Maybe we could add docs to https://intermine.readthedocs.io/en/latest/webapp/blue-genes/ to list which property is used by bluegenes.
