### ISSUE TITLE
When there's no default mine, don't have empty entries in the mine selector

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#241]
See what I mean?

![image](https://user-images.githubusercontent.com/9271438/37839054-705de76c-2eb1-11e8-9c16-6e19f6dd2fe3.png)

It's probably because there's a default {} empty map being added to the mines list in app-db

**Comment by sehgalvibhor** [comment]
@yochannah : I can still replicate this bug.
![image](https://user-images.githubusercontent.com/10993808/50422701-7b556a00-0872-11e9-95a9-f99bcae45f7c.png)

**Comment by yochannah** [comment]
I *think* this is actually due to InterMines that have a blank name in their properties file

**Comment by yochannah** [comment]
I think this is now fixed thanks to https://github.com/intermine/bluegenes/pull/337/commits/19a0b99b07a904e440bbbfe5f2ddd63051ec6729
