### ISSUE TITLE
Stand alone (default) mine does not fetch an anonymous token

### ISSUE THREAD

**Issue by joshkh** [intermine/bluegenes#244]
When running BlueGenes with a default service root, an anonymous token is not fetched and items can not be saved.

```bash
$ BLUEGENES_DEFAULT_SERVICE_ROOT=http://beta.flymine.org/beta lein run
```

![image](https://user-images.githubusercontent.com/4752532/39515201-4b052a2a-4df1-11e8-81f8-6b4d2dac0029.png)

**Comment by yochannah** [comment]
I can't reproduce this. Let's re-open if needed
