### ISSUE TITLE
homologue links - don't always show loading

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#250]
The little loading flower never seems to go away anymore. Why not? 

![image](https://user-images.githubusercontent.com/9271438/40919428-5e3a5988-6801-11e8-8773-402240ea922c.png)

code will be here: https://github.com/intermine/bluegenes/tree/dev/src/cljs/bluegenes/sections/reportpage/components - homologues or minelinks

**Comment by sehgalvibhor** [comment]
Looking into this!

**Comment by sehgalvibhor** [comment]
I am not able to replicate this on my system, can you help me replicating this?

**Comment by yochannah** [comment]
Homologues will be migrated to the homology tool.
