### ISSUE TITLE
Readme is chaotic

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#256]
fix it.

**Comment by yochannah** [comment]
add npm to the requirements for running bluegenes

**Comment by yochannah** [comment]
@sergiocontrino @julie-sullivan @danielabutano Can one of you lovely people tell me if things are a bit clearer now? I've broken things out of the readme into discrete files in the [docs](../blob/dev/docs) folder

**Comment by sergiocontrino** [comment]
@yochannah , it looks fine to me, thanks!

**Comment by yochannah** [comment]
Perfect, thanks!
