### ISSUE TITLE
Query Builder - can we fix the dodgy regex that doesn't detect acronyms very well? 

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#263]
See screenshot - CDSs and URTs should be one "word", not separated out to two words. If the regex for this is handled on the bluegenes side, maybe we can assert that all-caps words with or without and s at the end shouldn't be split in any way? Reported by @nuin

![image](https://user-images.githubusercontent.com/9271438/42386936-cc347ff4-8138-11e8-9fa7-9ceeac200821.png)

**Comment by yochannah** [comment]
This is where the magic happens: https://github.com/intermine/bluegenes/blob/bea9ed7b70a8f4a31cb78a5e11fdd4de16fa5ef7/src/cljs/bluegenes/utils.cljs#L4

**Comment by sergiocontrino** [comment]
UTRs and CDSs looks fine now, closing.
