### ISSUE TITLE
Add data sources page

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#264]
This is the human mine data sources page: http://www.humanmine.org/humanmine/dataCategories.do

Right now every InterMine does this manually, but it is possible to do programatically. Example: https://calm-earth-98875.herokuapp.com/ 

I'd suggest adding a link in the footer of BlueGenes to this, unless anyone else has other ideas.

**Comment by harleo** [comment]
Hey Yo how you doing?
I'll try to help out with a few small things.

**Comment by harleo** [comment]
PR is #284.

**Comment by yochannah** [comment]
@harleo Hey, nice to see you again! I have a couple ofsuggestions for improvement but they require work on my end (1. I'd like to launch that app on an intermine server rather than a free heroku instance and 2. it would probably be nicer to link to the data sets for an invidivual intermine rather than _all_ the data sets but I don't think the data set browser supports that). I'll leave this open for a bit while I sort things out.

**Comment by harleo** [comment]
@yochannah I see, I see. That would make more sense. I'll come back once you have things ready and I'll see if I can help out :)

**Comment by heralden** [comment]
We will instead create a page with an im-table running a query to show information on data sources.

Or a button in the UI (perhaps frontpage) which runs a query for the datasets.
