### ISSUE TITLE
Amend default initial styling to show a message indicating the less needs to be compiled again

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#276]
Let's make dev's lives easier. If there's been a `lein clean` in between the last time the less was compiled and the time they launched their browser to connect to a dev version of bluegenes, the page appears unstyled and messy, like this:

![image](https://user-images.githubusercontent.com/9271438/45491040-9fc48500-b760-11e8-89d3-704330b296fb.png)

This confuses everyone. Let's add a message along the lines of "If you're seeing this, it probably means your css isn't compiled".

Try not to make this appear for naive users, or at least make it a nicely reportable error so they know what to do if they see it. (One thought: use css to fade the error message in a few seconds after page load?)

**Comment by sehgalvibhor** [comment]
@yochannah : I have a fix for this. But a quick question, Do you think a message would suffice or should we display a loading bar similar to the one already implemented until the CSS files have been compiled?

**Comment by yochannah** [comment]
I'd suggest something explicit - e.g. "This page is missing its stylesheet. Please tell your administrator to run `lein less once`". Theoretically this should only appear for people who are compiling it locally and _not_ for users, so having a clear message what's going wrong would help. 

(Reason for this: whenever anyone developer-ey tries to test BlueGenes releases / bugfixes, etc, if they forget to compile the less, they come and ask me what's wrong.... This might save time, but is only intended for users who are also devs.)

Does that help?

**Comment by yochannah** [comment]
Oops, forgot to add: _not_ a loading bar, as it might give the dev the impression that they just need to wait in order for the css to compile when in reality they need to run a command themselves :)

**Comment by sehgalvibhor** [comment]
Makes sense! Yeah, I agree to what you stated. I'll make it like an alert maybe (similar to the one currently being implemented) to ensure style consistency.
