### ISSUE TITLE
Report page performance is still pretty dire

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#277]
Loading tens of im-tables automatically just probably is never going to be good. I'd suggest a re-think and possibly a tabbed interface.

**Comment by yochannah** [comment]
A sub component of this is splitting things up into sub-headings (copy what's currently in intermine jsp pages for the chunking, please!) and allowing this to be configured somehow. tool api tools could have default locations or be similarly configured.

**Comment by sehgalvibhor** [comment]
Just my two cents, one way could be to make these im-tables to load/expand only when you click on the header of the. Basically, 'Click to Expand' this might save the loading time, improve the performance and reduce massive window size.

**Comment by yochannah** [comment]
This is actually one possibility! The JSP-based intermine UI works this way, and it's something we might implement if there's no other way. 

I also feel like just dumping _everything_ on to one page isn't the best answer, and we might be able to make the page layout smarter. I'm not sure if that's what our users want, though, so we'll need to have a bit of a think.

**Comment by heralden** [comment]
[im-tables-3](https://github.com/intermine/im-tables-3/) seems pretty well thought out in regards to performance. When it's included in bluegenes, it's used as if it was part of the re-frame app, not as a separate webapp. It also initially renders itself as dumb html, until it's moused over and it re-renders as an interactive react/re-frame component. So I think our only choice is to reduce the amount of elements we show on a page.

I gave a different page layout some thinking and tried my hand at sketching a design. I went for the typical dashboard layout you see nowadays, with a sidebar that allows you to display/hide whole categories or specific aspects into the viewer to the right. Each block in the viewer corresponders to one subheader in the JSP-based InterMine UI, and they will build downwards like in a masonry layout. (Some blocks will probably need to span the entire length, for aspects that demand a lot of width.)

![bgd-desktop](https://user-images.githubusercontent.com/3865590/59504321-98224000-8e9a-11e9-929a-9cc38ea0a705.png)

I sketched mobile versions of the design. The viewer will be responsive, so on a mobile screen you'll probably only fit a single block horizontally. The aspect selector would be collapsible from the top and toggled by tapping the report title (*Gene: ARSD* in this case). The menu panel would also be collapsible and toggled by tapping the hamburger icon.

![bgd-mobile](https://user-images.githubusercontent.com/3865590/59504329-9e182100-8e9a-11e9-8e14-f41600617d0a.png)

![bgd-mobile-aspect-selector](https://user-images.githubusercontent.com/3865590/59504332-a1aba800-8e9a-11e9-9d38-00538980ef76.png)

![bgd-mobile-menu-panel](https://user-images.githubusercontent.com/3865590/59504335-a5d7c580-8e9a-11e9-95c1-7c9c1051c059.png)

**Comment by yochannah** [comment]
hardcode this layout initially, but later this will be configurable and able to put on the webservice.

**Comment by heralden** [comment]
Closing this issue for it to be continued in #393.
