### ISSUE TITLE
Set up Travis CI [Clojure + some bash knowledge required]

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#282]
Bluegenes doesn't have as many tests as it should, and we need to fix this. A good start would be to set up CI and get things automatically running. 

**Task:** 

1. Comment on this issue to say you're picking it up. 
2. Set up Travis (or some other CI) to build the [minified](https://github.com/intermine/bluegenes/blob/dev/docs/production-builds.md#testing-a-minified-instance-before-deploying) version of BlueGenes every time a push is made. The documentation for setting BlueGenes up is here: [https://github.com/intermine/bluegenes#setting-up-your-dev-environment-and-running-bluegenes](https://github.com/intermine/bluegenes#setting-up-your-dev-environment-and-running-bluegenes). Use the `dev` branch to do this. 
2. Make a pull request when you're ready! 

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [discord](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by glc-mvion** [comment]
Hello ! :wave: 

I would like to grab this issue (:

**Comment by yochannah** [comment]
@MattMattV Awesome! Ping me if you have any Qs

**Comment by yochannah** [comment]
Fixed by https://github.com/intermine/bluegenes/pull/285 :100:
