### ISSUE TITLE
Migrate from bower to npm

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#283]
[Bower is basically deprecated these days](https://bower.io/), and all the packages available in bower.json are available on npm anyway. Let's get rid of the extra dependency. 

### Task
1. Comment on this issue to let us know you're working on it! 
1. download and install bluegenes - [guide](https://github.com/intermine/bluegenes/blob/dev/docs/getting-started.md)
2. have a quick browse of the various pages to get an idea of what they look like before we migrate the packages (they're mostly css related packages rather than functionality related packages). 
2. look at the items in [bower.json](https://github.com/intermine/bluegenes/blob/dev/bower.json) and install them via npm instead. Delete bower json. 
3. Make sure things still look the same - i.e. that we didn't break anything with the migration. 
3. Make a pull request! 

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by SergioMD15** [comment]
I'll work on this

**Comment by yochannah** [comment]
@SergioMD15 Awesome! Let me know if you have any questions or issues :+1:

**Comment by yochannah** [comment]
@SergioMD15 Any luck with this? :)

**Comment by SergioMD15** [comment]
Sorry, I wasn't able to do it

**Comment by heralden** [comment]
I just added a PR for this [=

**Comment by yochannah** [comment]
I merged this too early, as @uosl pointed out - some of the scripts aren't linked properly as they'rebelow the server's public root

**Comment by heralden** [comment]
I created a new PR https://github.com/intermine/bluegenes/pull/294 so hopefully this should end this chapter. [[=
