### ISSUE TITLE
replace rawgit image links with github image links [clojure / hiccup]

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#287]
We used rawgit to serve some image files in Bluegenes, but [RawGit is being shut down](https://rawgit.com/). There are a few links in BlueGenes that use RawGit to serve the images. They aren't strictly necessary, as GitHub allows hotlinking to images  - i.e. 

this URL: https://cdn.rawgit.com/intermine/design-materials/master/logos/intermine/intermine.png will resolve to https://raw.githubusercontent.com/intermine/design-materials/master/logos/intermine/intermine.png when you paste the original URL in your browser.

### Task: 

Search BlueGenes for all occurences of rawgit urls (I can find three) and replace them with the raw.githubusercontent.com URLS they resolve to instead.

#### If you would like to pick this up

Please comment on the issue to say you're making the changes! Then fork the repo, make the changes, and make a pull request.

#### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by gdevincenzi** [comment]
Hey @yochannah 
I'd like to give this one a shot, is that ok?

**Comment by yochannah** [comment]
@gdevincenzi Thanks! At initial glance it looks great - I'll merge it after the weekend :) 👍
