### ISSUE TITLE
ID resolve default config - support old and new config style

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#288]
The ID resolver component uses the web-properties endpoint to fetch defaults for the ID resolver, among others things. 

The bag endpoint results used to look like this: 

```json
    "bag": {
      "results": {
        "table": {
          "size": "5"
        }
      },
      "example": {
        "identifiers": "CG9151, FBgn0000099, CG3629, TfIIB, Mad, CG1775, CG2262, TWIST_DROME, tinman, runt, E2f, CG8817, FBgn0010433, CG9786, CG1034, ftz, FBgn0024250, FBgn0001251, tll, CG1374, CG33473, ato, so, CG16738, tramtrack,  CG2328, gt"
      }
    }
```

Note `bag.example.identifiers`. Newer versions of the config look like this: 

```json
    "bag": {
      "results": {
        "table": {
          "size": "5"
        }
      },
      "example": {
        "identifiers": {
          "default": "PPARG, FTO, 3949, LEP, 946, MC3R, 9607, LPL, LDLR, P55916, 335, GLUT4, Notch1, SLC27A1",
          "protein": "P37231, PPARG_HUMAN"
        }
      }
    }
```
We now have bag.example.identifiers, with subchildren `default` (this maps to Gene for legacy reasons) and `protein`. This is potentially infinitely extensible to however many child class properties we wish. 

Right now BlueGenes only supports the first option I think. We should support both.

The relevant file to change is here: https://github.com/intermine/bluegenes/blob/2eeb54e5ab2d03f32802593b2a90ba6dee4c4749/src/cljs/bluegenes/events/webproperties.cljs#L16 where we store the exaample to the app-db.

**Comment by allentiak** [comment]
@yochannah 
I will take a look at this.

**Comment by yochannah** [comment]
@allentiak nice one! Ping me with any questions

**Comment by allentiak** [comment]
@yochannah
Could you please assign this one to me, so I can eventually convert it into a PR?

**Comment by yochannah** [comment]
@allentiak GitHub doesn't actually allow issues to be assigned to anyone unless they're members / owners of the repo. Feel free to consider this "yours" though - and you can also [reference the issue from your PR / commits if you like](https://help.github.com/en/articles/autolinked-references-and-urls).

**Comment by allentiak** [comment]
OK

**Comment by heralden** [comment]
Fixed in https://github.com/intermine/bluegenes/commit/3c94f5e123ff9fda8a9dd7af8fb7208293f46317
