### ISSUE TITLE
Regionsearch label alignment not always correct

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#29]
examples: 

![image](https://cloud.githubusercontent.com/assets/9271438/21810090/4424dd44-d742-11e6-9b93-a6044e7ac737.png)

![image](https://cloud.githubusercontent.com/assets/9271438/21810173/8dfc1324-d742-11e6-8e29-37541622e614.png)

**Comment by yochannah** [comment]
I think this happens when the features don't overlap the original regions on both sides.

**Comment by yochannah** [comment]
Correcting the min-max stops the labels overflowing, but it becomes clear that the math is out somewhere for these. 

For flymine's third defaut region there should be three chunks of different overlapping features. The features marked below in yellow and purple overlap almost perfectly, as do the blue and green, hence why there are 5 overlaps in total but only three separate chunks should be seen on the diagram, assuming I've done my math correctly. (Please yell at me if I haven't).This is *not* to scale, I did it in a paint program, and the regions should all be about the same length

![image](https://cloud.githubusercontent.com/assets/9271438/22065351/c9345012-dd7f-11e6-916c-cbd95a455cce.png)

We also need to remove or reduce the blur, but this doesn't fully fix the problem. Short term: I'm removing the graphs from the display. 

Longer term: make sure the clculations are fully tested, esp. for boundaries and scenarios where there aren't overlaps on both sides of the region.

**Comment by yochannah** [comment]
ok, removing blur and allowing the min-start and max-end values to be part of the original set has made things better, but I don't think that the left two should overlap :/ 

![image](https://cloud.githubusercontent.com/assets/9271438/22068253/5f595ac2-dd8c-11e6-8a72-b8d91a0e8938.png)

**Comment by sehgalvibhor** [comment]
@yochannah : How can I replicate this on the dev environment?

**Comment by yochannah** [comment]
@sehgalvibhor Good question! I had to dig a little to remember (note to self: always include file locations when you make tickets!)

Uncomment this line: https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/pages/regions/results.cljs#L82 that should do it! 

P.S. sorry for the slow reply, I"ve been out of the office travelling! :)

**Comment by yochannah** [comment]
this issue is no longer valid - we removed the graph since it wasn't valid
