### ISSUE TITLE
Enforce formatting as part of CI build

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#295]
We have a nice formatting task, `lein format` to keep code tidy now thanks to https://github.com/intermine/bluegenes/pull/291 :1st_place_medal: 

It would be nice to either automatically apply the formatting in some way, or if this isn't easy, then simply fail travis builds if the formatter hasn't been applied before committing and pushing.

**Comment by yochannah** [comment]
See https://github.com/intermine/bluegenes/pull/291#issuecomment-435593044 for preferred approach!

**Comment by sehgalvibhor** [comment]
@yochannah : I think if we can set up a pre-commit hook to ensure code formatting before every commit. Might be a bit complicated but can try. Let me know your thoughts!

**Comment by yochannah** [comment]
That's okay - I think what you've done is perfect. The commit hook probably isn't necessary. :+1:
