### ISSUE TITLE
Gradle-launched bluegenes + tool API - token expiry message won't go away.

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#299]
See https://github.com/intermine/bluegenes/pull/278#issuecomment-441027803

Maybe look at #133 and #292 as well

**Comment by yochannah** [comment]
@julie-sullivan you reported this initially, but I'm having trouble replicating it. I've tried on both local/dev versions and gradle-launched versions of bluegenes. Can you try deleting your local storage and reloading the page? 

On a strongly related note, I'm not sure that aggressive red message is needed at all - we have an issue open to make it less annoying: 

https://github.com/intermine/bluegenes/issues/292

If the cache delete fixes things I'll close this issue.

**Comment by yochannah** [comment]
@julie-sullivan I have a truly silly question here. Did you press the refresh button in the error notification, when you got this error?

**Comment by julie-sullivan** [comment]
I think so! 

I haven't deleted storage though and tried again. Let me do that.

**Comment by yochannah** [comment]
Cache was the problem 🌮

**Comment by yochannah** [comment]
It wasn't really the cache. I think it was fixed here, maybe, hopefully, please: https://github.com/intermine/bluegenes/pull/337/commits/19a0b99b07a904e440bbbfe5f2ddd63051ec6729
