### ISSUE TITLE
consider implementing UI tests with cypress

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#309]
Recommended by @mb1096 as a more pleasant alternative to selenium. Demo repo in use: https://github.com/EBI-Metagenomics/ebi-metagenomics-client/ and demo test: https://github.com/EBI-Metagenomics/ebi-metagenomics-client/blob/master/cypress/integration/login.js

This could initially be populated with tests from the [PR checklist](https://github.com/intermine/bluegenes/blob/dev/PULL_REQUEST_TEMPLATE.md), and merged into travis ci

**Comment by sehgalvibhor** [comment]
@yochannah : I am working on this. However, I am not sure how to replicate 'ID resolver + results preview' condition for the PR checklist. Can you help me with this?

**Comment by yochannah** [comment]
@sehgalvibhor :gem: you are a gem! Sorry, the ID resolver thing isn't quite clear, is it? It's referring to the upload section, checking that it works correctly and shows all resolved identifiers - i.e. I clicked on the example button in the upload page, then moved on to this page: 

![image](https://user-images.githubusercontent.com/9271438/50345356-a6fceb00-0526-11e9-89f8-61b19d5d12eb.png)

Using the example IDs (for flymine) if the page has 1 converted, 2 synonyms, and 1 ambiguous, as well as the 22 matches, I'd consider the test passing. For travis, we'd need to figure out how to make this test work for the test mine: https://intermin e.readthedocs.io/en/latest/get-started/testmine/, and longer term for any mine, somehow (but the test mine alone should suffice, I think.)

**Comment by yochannah** [comment]
I've renamed it to upload on the PR template, so I hope it's clearer now!

**Comment by sehgalvibhor** [comment]
Thanks! I am trying, I'll let you know in case I get stuck :)
One another thing, for ```Login and logout works for more than one user (use test user demo@intermine.org pw demo if needed)```

Are these test user details working across all the different mines, because when I try this in Beanmine, it gives a 401. And how should we test it for multiple users (do we even need it?), just wanted to understand the reasoning here :)

**Comment by yochannah** [comment]
ahh - demo/demo is only present on flymine and humanmine I think.

Re the need to check more than one user - this was due to a strange bug in
bluegenes that I can't see documented anywhere, where known users to
bluegenes could log in, but no other users could log in, even if they were
registered in the relevant intermine. I'm a bit annoyed at past me for not
making a ticket about it so I could remember the details better! :)

**Comment by sehgalvibhor** [comment]
Okay, so I am confused. Just to clarify, the UI tests should be independent of the mine loaded right? I mean, we just basically need to check whether the basic functionality is still working or not after the code changes have been made. Example: Cypress opens homepage -> Clicks Region -> Clicks Show Example -> Clicks Search -> Asserts whether the Results are present and POST request responds with a 200. This is completely independent of which mine has been loaded.

**Comment by yochannah** [comment]
You're right! That's probably sufficient as a test and a good way of making sure that we aren't tied to a single mine.

**Comment by sehgalvibhor** [comment]
Okay, got it. I am doing something on the similar lines except for the Login test, I change the mine to Flymine and test with the demo user details.
