### ISSUE TITLE
List of Lists (My Data) page should show list description

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#313]
See this page in humanmine - there are list descriptions in the list page

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/9271438/50520266-438b3400-0ab7-11e9-8fae-244eeae1b702.png">

We should add this to BlueGenes, too.

**Comment by sehgalvibhor** [comment]
@yochannah : Added this (PR soon?). Screenshot below: 
![image](https://user-images.githubusercontent.com/10993808/50534021-f745ff80-0b5b-11e9-90d9-72f45e845441.png)

Long lines of text preview:
![image](https://user-images.githubusercontent.com/10993808/50534044-63286800-0b5c-11e9-8194-ca63136d2fdc.png)


But, do you notice how the labels are becoming now? With so much white space on top and bottom as soon as you add the text. Should I leave it like that for now?
