### ISSUE TITLE
Template constraints not always offering all the constraint options you might expect.

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#32]
for example, we might expect to see equals in the dropdown list:

![image](https://cloud.githubusercontent.com/assets/9271438/21813199/5d0d301c-d74d-11e6-934f-9afaab51d3cb.png)

Possible place to start looking: https://github.com/intermine/redgenes/blob/dev/src/cljs/redgenes/components/ui/constraint.cljs#L7

**Comment by joshkh** [comment]
This is because the constraint "Probe Set" is at the class level, not the attribute level, so the constraint is limited to "LOOKUP" operators and list operators. This is in line with Intermine 1's behaviour.

**Comment by yochannah** [comment]
Rachel has also commented "Optional constraints are missing from templates (e.g. Gene → Orthologues)."

**Comment by yochannah** [comment]
@joshkh did we add optional constraints at some point or is it still to-do?

**Comment by joshkh** [comment]
@yochannah Yup, templates now have optional constraints:

![image](https://user-images.githubusercontent.com/4752532/37600607-b2880148-2b7f-11e8-9c1f-cea2c3f72b52.png)

**Comment by yochannah** [comment]
:boom: Issue is ded.
