### ISSUE TITLE
Footer and web content overlapping

### ISSUE THREAD

**Issue by sehgalvibhor** [intermine/bluegenes#323]
The footer text is somehow overlapping with the web content.

![image](https://user-images.githubusercontent.com/10993808/51842445-eb09b980-2336-11e9-89df-47deab42f2ac.png)

**Comment by Xxyumi-hub** [comment]
Hi! I'm an outreachy application, can I work this?

**Comment by heralden** [comment]
@Xxyumi-hub Sure, go ahead.
