### ISSUE TITLE
Project Setup Issue

### ISSUE THREAD

**Issue by Zemotacqy** [intermine/bluegenes#324]
I was setting up the project in my local machine (Ubuntu 18.04) following [this](https://github.com/intermine/bluegenes/blob/dev/docs/getting-started.md) 

1. I installed Leiningen  NO Issue
2. Compile the CSS using `lein less once` NO Issue
3. Start the process: `lein figwheel dev` [Error](https://pastebin.com/LJRJzpT2) Occured 
Upon searching, I fixed the issue by Adding this code at Line 105 in /project.clj  `:jvm-opts ["--add-modules" "java.xml.bind"]`
Could this be an issue from my side?
I am not familiar with Clojure but since I faced this issue, I thought it would be better to notify the community.

**Comment by yochannah** [comment]
@Zemotacqy Thanks for flagging this up! 

I think this is something we need to add for longer-term Java 9+ support.

**Comment by yochannah** [comment]
hmmm, the problem is that including that line on java 8 results in java 8 builds failing 😅 I'll see if there's a way to conditionally include it.

**Comment by yochannah** [comment]
Okay, I've added an optional profile to allow people to specify they're using java 9. Could you possibly test it for me @Zemotacqy? 

1. Stash or commit any changes you had to project.clj. 
2. Pull https://github.com/yochannah/bluegenes/tree/java-9 
3. try running `lein with-profile +java9 figwheel` - this should allow you to specify the module option you need, without forcing people still using java 8 to run it. Let me know if it works, and if so I'll add it to the tutorial and docs!

**Comment by Zemotacqy** [comment]
Sure @yochannah , I am on it

**Comment by Zemotacqy** [comment]
@yochannah  It worked :smiley: I executed the following commands:
`lein with-profile +java9 figwheel`
followed by
`lein with-profile +dev run`
and it did run successfully

**Comment by yochannah** [comment]
@Zemotacqy  Hurrah! Thank you so much for testing this! I'll update the docs and merge in #325 next week at it's hometime now - have a great weekend :)

**Comment by Zemotacqy** [comment]
Thank you @yochannah I am glad I could help in any way possible.

**Comment by yochannah** [comment]
Okay, this is fixed and merged. I clearly have a lax view of what "next week" means 🤦‍♂️
