### ISSUE TITLE
migrate tool api server to its own package

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#327]
The tool api server will also need to be used by the InterMine Creator, for the tool selection step. It won't be too hard to migrate it to its own package, and package it up as a JAR so that @julie-sullivan can use it to serve the tools to the creator.

**Comment by heralden** [comment]
As a note, this API seems already fairly self-contained in `src/clj/bluegenes/ws/tools.clj`, so it shouldn't be too much work to separate it out.
