### ISSUE TITLE
Account Registration Link Not Working

### ISSUE THREAD

**Issue by lazycipher** [intermine/bluegenes#328]
**Description**

I was trying to sign up on BlueGenes and found that the link to register a new account isn't working as expected.

When user clicks on `Register`, the page redirects to `createaccount.do` instead of the actual url on [demo instance](bluegenes.apps.intermine.org/).

While on localhost, the same `Register` button redirects user to 
`http://https//mines.legumeinfo.org/beanmine/createAccount.do`
instead of redirecting to 
`https://mines.legumeinfo.org/beanmine/createAccount.do`

**Expected Behavioir**

`Register` button should redirect user to correct sign up page.

**Additional Information**
I'm willing to work on this.

**Comment by yochannah** [comment]
Feel free to take a look at this if you like!

**Comment by yochannah** [comment]
I believe this is fixed as part of work to implement the InterMine registry in Bluegenes, ticket #151 - not deployed to prod yet though.
