### ISSUE TITLE
Cypress testing: Test with and without a default URL

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#338]

**Comment by yochannah** [comment]
This command would do it: 

```BLUEGENES_DEFAULT_SERVICE_ROOT=http://beta.flymine.org/beta lein run ```

**Comment by heralden** [comment]
All CI now is testing with `BLUEGENES_DEFAULT_SERVICE_ROOT` set to a biotestmine started with https://github.com/intermine/intermine_boot. I don't think it's worth it to test without a default URL as well due to the extra runtime and possible connection issues it would add.
