### ISSUE TITLE
Cypress Docker container fails to start

### ISSUE THREAD

**Issue by allentiak** [intermine/bluegenes#340]
I get a "failed dependencies" error.

I see there are many warnings of renamed/deprecated dependencies: more details in
https://travis-ci.org/intermine/bluegenes/builds/526651495

**Comment by yochannah** [comment]
Travis has been flaky as anything lately (sometimes failing on JDK installs, which is something travis is responsible for, not our scripts), so it might actually work now (and the cypress step is working for me on other branches). 

Could you try again?

**Comment by yochannah** [comment]
There was *also* another issue with a dependency for Codox that has been fixed - it'll hopefully soon be in dev, or you could just cherry-pick https://github.com/yochannah/bluegenes/commit/84f7dc073b3e5273277432b26847aa46481e87ff

**Comment by yochannah** [comment]
Update - I managed to reproduce it! Frustratingly, the _same_ push failed once and succeeded once on Travis. I can only assume the builds were carried out on different but similar machines or something. Anyway, I *think* I've fixed the script so it will install those dependencies whether or not we need them. Pull dev!

**Comment by yochannah** [comment]
I haven't seen this fail again so I'm assuming it's fixed.
