### ISSUE TITLE
Add build support for "LTS-stable" OpenJDK 11

### ISSUE THREAD

**Issue by allentiak** [intermine/bluegenes#341]
Falling back to "oldstable" OpenJDK 8...

**Comment by allentiak** [comment]
TODO: check this.

**Comment by yochannah** [comment]
Thanks for reporting this, @allentiak! We have a profile for OpenJDK 9 but I haven't tested it with anything higher yet. Hopefully there won't be too many more breaking changes between JDK versions!

**Comment by allentiak** [comment]
I would advise you to focus on LTS OpenJDK releases, while increasingly
supporting newer short-term releases. This combination will allow you to
reduce the eventual delta with the yet-to-come newer LTSs.

The current LTS version 11. Both versions 9 and 10 are not supported
anymore. In general, Non-LTS releases are moving targets, to be supported
until the next one comes (every six months). AFAIK, the next LTS should be
version 17 (AKA 21.9 in the new visioning scheme).

I advise you to read the current OpenJDK release policy (if you haven't
already :-)

>

**Comment by yochannah** [comment]
That's a really good idea, and I wasn't aware that 11 was the current LTS. Thank you!!

**Comment by yochannah** [comment]
Adding in this handy-looking Java 11 upgrade guide: https://www.deps.co/blog/how-to-upgrade-clojure-projects-to-use-java-11/

**Comment by allentiak** [comment]
In case OpenJDK 11 is not bundled with your OS, you can download binary builds from here: https://adoptopenjdk.net/

**Comment by allentiak** [comment]
FYI: https://www.deps.co/guides/travis-ci-latest-java/

**Comment by heralden** [comment]
Fixed with https://github.com/intermine/bluegenes/pull/499
