### ISSUE TITLE
GitLab will start charging for CI support for GitHub on 2019.09.23

### ISSUE THREAD

**Issue by allentiak** [intermine/bluegenes#349]
JFYTK...

See "Plans and Pricing" section of 
https://about.gitlab.com/solutions/github/

**Comment by yochannah** [comment]
oh, poo. I only just set that up, too! :laughing: I'll leave this open 'til the change happens, then we can see if there's any workaround or if we just need to remove the integration. Thanks for letting us know!

**Comment by sehgalvibhor** [comment]
> Open source projects
If you have a public, open source project on GitHub you can now take advantage of free CI/CD on GitLab.com. As part of our commitment to open source, we offer all public projects our highest tier features (Gold) for free. While other CI/CD vendors limit you to running a handful of concurrent jobs, GitLab.com gives open source projects hundreds of concurrent jobs with 50,000 free CI pipeline minutes.

IMHO, It should still be free for open source projects (ideally the project should already be on Gold plan). The plan shift/pricing is only for 'Free' account holders.

**Comment by yochannah** [comment]
tested now - this doesn't appear to be an issue since we're open source, as @sehgalvibhor suggested
