### ISSUE TITLE
Remove re-frisk dev tool

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#353]
Since we've added `re-frame-10x` which has an app-db explorer, there seems to be no reason to include `re-frisk` anymore.

**Comment by yochannah** [comment]
nuke it! :D

**Comment by yochannah** [comment]
@uosl am I right in thinking one of your PRs already did this?

**Comment by heralden** [comment]
Nope! [=

One useful feature I've discovered with re-frisk however, is that since it's always enabled on dev, the application state will be browseable at any time. This isn't true for re-frame-10x, as it will only be enabled while the panel is open. So if you suddenly decide to explore app-db, but didn't open the panel when you started the web app, it won't be available in re-frame-10x unless you refresh, starting the state from scratch (or localstorage).

**Comment by yochannah** [comment]
okay - should we leave it in and close this issue, then?

**Comment by heralden** [comment]
Yes. I found another useful feature: re-frisk stays alive when things crash and burn (uncaught error) while re-frame-10x's app-db explorer dies.

We'll keep re-frisk, and I'll close this issue.
