### ISSUE TITLE
better tool folder management for dokku

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#361]
Currently we enter the docker container and npm install the tools: https://github.com/intermine/bluegenes/blob/dev/docs/tools/dokku-tool-installation.md 

I have a feeling this might nuke the tools every time we redeploy. What is a better solution? 

- Figure out how to specify a tools folder outside container? Will that allow updates to the external folder that automatically reapply to bluegenes? I think dokku allows us to link eternal volumes somehow
- script npm installing everyhing in the tool folder's package json, post-install. This has the advantage of being low effort, and we could still enter the container if we want to install a tool without redeploying bluegenes. 
- other, smarter idea?

**Comment by josegonzalez** [comment]
If you use the nodejs buildpack and have a `scripts.build` key in your package.json, that will run during the build process. There are actually [a few other script keys](https://github.com/heroku/heroku-buildpack-nodejs/blob/6f7e7e2115cfbca7b38cc18fa798e57244ee7698/lib/dependencies.sh#L56) that are installed, though it might be easier to find some official documentation on the Heroku buildpack for your particular use-case.

Dokku supports [persistent storage](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/), though - by default - it is not mounted during the build process.

Hope that helps.
