### ISSUE TITLE
Tool API: Should we always use "ids" instead of "list"?

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#379]
In #378 I added support for `accept: "list"` in tool's `config.json`.

Something that is unfortunate is that when you create your own list (e.g. by building a query or narrowing down your list using a widget), a tool that only accepts list names (`"list"`) won't work anymore. 

One way to solve this would be to save everything as a list so that Tools that use `"list"` can always acquire them. But this would probably be a bad solution, as it would produce a lot of garbage lists.

The other and probably better way would be to force tools to use `"ids"` instead, by removing the option for `"list"`. We will always be able to produce IDs from a list, but not vice versa. This way, we won't end up with tools that only work with one type, which seems broken to the user as both types are displayed similarly in the UI.

@yochannah hope you can check this out when you're back.

**Comment by yochannah** [comment]
I think I 100% agree with this plan. lists can always become ids, ids can't become list, so we should stick to ids.
