### ISSUE TITLE
Login & registration web services - provide current specs

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#391]
We can begin to build proper registration and login pages for BlueGenes even before #390 is ready, so long as we have API specs.

**Comment by danielabutano** [comment]
The new /service/login web service receives (in the body of the request) 2 parameters  username and password.
See https://github.com/intermine/intermine/issues/1650

**Comment by danielabutano** [comment]
Updated the current /users webservice to allow to attach the anonymously created lists to the user just created. See https://github.com/intermine/intermine/issues/2149
