### ISSUE TITLE
Report page - prototype dashboard layout.

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#393]
in no particular order: (some of these may become issues on their own)

- [ ] user test prototypes
- [ ] design config to enable layout
- [ ] match existing Aspect config to the BlueGenes config
- [ ] script migration from Aspect -> BlueGenes where relevant
 
This will affect or be influenced by #43, #45, #127, #134, #277

**Comment by heralden** [comment]
Suggestion for layout can be found here https://github.com/intermine/bluegenes/issues/277#issuecomment-502065871.
