### ISSUE TITLE
Remove highlight search term feature

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#396]
We know it's slow. Perhaps with some work we can make it faster. But I know for sure it won't beat any browsers implementation of `Ctrl+F`, which also gives you a count of how many matches and lets you jump between them.

If everybody and their grandmother doesn't know about `Ctrl+F`, we could maybe write it down somewhere on the search page. (Hopefully in a container hidden on mobile screens, so we don't make a fool of ourselves.)

What's your thoughts, @yochannah.

**Comment by yochannah** [comment]
In this case, (after some careful email searching) this was a feature that was explicitly requested by Rachel, so it should be left in, and improved, rather than removed. Do you mind if I close this issue?

**Comment by heralden** [comment]
Before you do that, can @rachellyne check this issue out?

If you still think it's necessary, you can close it, and I'll try to improve it.
