### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/bluegenes#402]
can we deploy and test bluegenes on https? Tell @kkarra!

**Comment by julie-sullivan** [comment]
https://ring-clojure.github.io/ring/ring.adapter.jetty.html 
should just be able to set:
```
:ssl? true
```

**Comment by heralden** [comment]
@kkarra
I see that the production mines use Apache or Nginx in front of apache tomcat serving Intermine, so I think it would be best to use the same Apache or Nginx webserver as a reverse proxy to bluegenes. This would make supporting HTTPS straightforward, in line with how I'm guessing it's done for the intermine webapp.

This is the recommended way of enabling HTTPS support for jetty apps. I'm closing the issue as this has to be done at the web server configuration. (Any of the standard documentation on configuring a reverse proxy applies for use with bluegenes as well.)

**Comment by kkarra** [comment]
Got it! we will be able to work that out. thanks!
