### ISSUE TITLE
What happens if there is no webapp available?

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/bluegenes#403]
From @AdrianBZG 

```
I can access bluegenes on port 5000, but only see the front page, none of the sections work
And gives a "empty response" error in console
Should <-------------> 0% EXECUTING [2m 59s] that actually change?
```
We think the issue is that stormmine was not running.

Is there a way to give a better error message in bluegenes? To indicate that we need a webapp to work?

**Comment by yochannah** [comment]
Closing this as a duplicate of #234 :) Thanks for reporting it, though! :+1:

**Comment by julie-sullivan** [comment]
Also, transcribing from @AdrianBZG in chat, he had the baseUrl as `localhost`, which caused errors.

Maybe we could add docs to https://intermine.readthedocs.io/en/latest/webapp/blue-genes/ to list which property is used by bluegenes.

@AdrianBZG I think after that change, it worked?

**Comment by AdrianBZG** [comment]
Yes indeed, after that it worked!
