### ISSUE TITLE
Report page: needs quick links

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#43]
Add quick links / data tabs to the top of the report page to help navigate long pages and give the user an idea of what data's available without having to scroll through it all. (Suggested by rachel)

**Comment by sehgalvibhor** [comment]
@yochannah : Might be a strange question, but how/from where do I generate these reports? I am not able to track this on the UI.

**Comment by Kirti2502** [comment]
I would like to work on this issue.

**Comment by heralden** [comment]
Hey @Kirti2502. The report page is awaiting a redesign, so unless you want to tackle the redesign, quick links is something we won't add currently.

**Comment by heralden** [comment]
Closing this issue to be managed further in #393.
