### ISSUE TITLE
add bioschemas metadata

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#430]
visit flymine.org and look for json ld in the root of the page for an example how to do this - the data are fetched by a webservice.

**Comment by heralden** [comment]
This will be need to be added to both the root and for each report page.

The web service is called `/service/semantic-markup/reportpage` and receice in input the intermine ID

Note that this will be challenging as Bluegenes is a SPA and the Bioschema is fetched by a crawler. We will likely need to handle this on the Bluegenes backend.

Edit: We could try first if the crawler is able to read pages generated from JS.

**Comment by danielabutano** [comment]
In the home page the service to call is `/service/semantic-markup/homepage`
