### ISSUE TITLE
Add perma share link

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#431]
see the share link on flymine.org to get the correct structure

**Comment by heralden** [comment]
We should use the http://iodocs.apps.intermine.org/flymine/docs#/ws-permanent-url/GET/permanent-url webservice to get a permalink from an object ID. Then we need to add a route in Bluegenes to handle this permanent URL (either `/minename/publication:2612903` or `/minename/perma/publication:2612903`).

Getting an object ID from the permalink can be done with a LOOKUP query on the class (Daniela will let us know if there are edge cases where this won't work).
