### ISSUE TITLE
Mine name disappears in navbar

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#440]
When selecting ThaleMine in the mine switcher, it will disappear from the top left of the navbar. (Perhaps because of some missing data from the registry?)

**Comment by yochannah** [comment]
On narrow window widths, the name should disappear from any mine and the icon/logo will be the only thing present. Is this possibly what's happening?

**Comment by heralden** [comment]
Looks like this was caused by the web-properties web service not working.
