### ISSUE TITLE
allow user to reset forgotten password

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#458]
People are human and forget or mistype passwords. We should allow them to reset it.

Depends on https://github.com/intermine/intermine/issues/2173

**Comment by noorfathima11** [comment]
Can you assign me this?

**Comment by Kirti2502** [comment]
I would like to work on this issue.

**Comment by heralden** [comment]
@noorfathima11 @Kirti2502 
This is something that needs to be implemented on the InterMine backend, so sadly there's no work to be done for it on Bluegenes until the webservice has been implemented. Sorry!
