### ISSUE TITLE
Support creating templates

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#460]
It doesn't seem like Bluegenes supports creating templates currently.

In JSP this is done with a button in the query builder, which opens the below section. We should probably provide a similar interface in Bluegenes.

Note that this is only available for logged in users.

![2020-01-10-113053_994x705_scrot](https://user-images.githubusercontent.com/3865590/72150122-b1418f80-339c-11ea-8b7e-f4eb87fbb5a4.png)

**Comment by noorfathima11** [comment]
Can you assign me this?

**Comment by heralden** [comment]
More stuff this will necessitate:
- [x] Edit template button when logged in
- [x] Re-fetch templates on login and logout
- [x] Delete template button when user owns the template (alert needs to include an **Undo** button, just like when deleting saved queries)
- [x] Filter on templates page to only show templates owned by the user
- [x] New panel in admin page to import/export templates (~~use includeBroken=true for listed templates here?~~ saved for future release #767)
- [x] Able to add/remove template tags (to set as `im:public` or `im:aspect:*`) when superuser and owns template (should be in new panel)
- [x] Precompute and summarise buttons when superuser and owns template (should be in new panel)
- [x] ~~If constraint description is now passed with JSON, display it when viewing a template, and allow editing from *create template*~~ Saved for future release

For stuff that requires new WS, make sure to include appropriate fallback behaviour!
