### ISSUE TITLE
Filter and sort lists in My Data

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#462]
It seems like this was present before (from looking at the source code) but not anymore, and I think we gravely need it.

**Examples**
*Filter: by fuzzy search, by type, by tags*
*Sort: by name, by date, by count, by type*
*Maybe have personal and public lists sectioned from each other?*

**Comment by heralden** [comment]
As a suggestion for design, I think putting this in a new sidepane to the left of the lists on the My Data page would be nice. Perhaps similar to how it looked with the old tag infrastructure.

![old-my-data](https://user-images.githubusercontent.com/3865590/72980402-6f6c0c80-3dd2-11ea-8c0b-841f30ca8e36.png)

**Comment by roshnidesigns** [comment]
It is clear that the 'tags' are not implemented til now in the current system or is it? and I might have not recognized it. If you could explain me the difference between tag and type once, that'd be great!

**Comment by heralden** [comment]
@tinycosmos It is correct that tags aren't implemented in the current system. It used to be implemented when Bluegenes had its own database, but that approach was dropped years ago.

It might be implemented in the near future though, using the Intermine's webservices and database (it is actually ready and we just need to implement it in Bluegenes interface).

**Tags** are added to lists by the user themselves. Multiple can be added to one list, and they can be added/removed at any time.
**Type** is what kind of data the list holds. When you create a list, you have to decide what its contents are. Is it a list of genes? A list of organisms? This is the type of the list, and it cannot be changed in a saved list. When two or more lists have the same type, this allows you to perform set operations on them, like creating a new list out of the genes common to two lists of genes (using the *Intersect* operation).

**Comment by roshnidesigns** [comment]
thanks @uosl  that clears a lot of things!
Another question just popped up, while creating a list we don't actually provide users option to set the _type_ and _tag_ on their own and if I'm not wrong this has to be implemented in the design along with the _date_ section.  Also what if user forgets to specify the type (maybe it's a very long list of data and one just can't decide)? or what if one makes list with different _types_ of data? Does the system itself specifies the _type_ in both cases mentioned ?

Related to options from context menu, _rename, delete and duplicate_ all of these features are accessible to public users. So, let me know if we are deciding on disabling any of the mentioned feature or users can be just allowed to operate on public lists as they want, which should not affect the main data i guess

**Comment by heralden** [comment]
> Another question just popped up, while creating a list we don't actually provide users option to set the _type_ and _tag_ on their own and if I'm not wrong this has to be implemented in the design along with the _date_ section. Also what if user forgets to specify the type (maybe it's a very long list of data and one just can't decide)? or what if one makes list with different _types_ of data? Does the system itself specifies the _type_ in both cases mentioned ?

I think we should look at the ways you can create a list. So when you use *Upload*, you have to decide the *List type* (you can try it out by leaving everything default, clicking *Example*, *Continue*, and then *Save List*). Another way to create lists is by running a query and saving the results by using *SAVE LIST* in the im-table. You are then presented with a dropdown of all the data types present in the list. It will also tell you how many there are of each; e.g. *Would you like to save a list of 25 Genes or 3 Organisms?*.

As far as I know, it's not possible to create a list without deciding on **one** data type for it. As for tags, we'll have to provide a feature to add tags to lists in the *My Data* page, so it's correct that this has to be implemented in the design along with other things missing.

> Related to options from context menu, _rename, delete and duplicate_ all of these features are accessible to public users. So, let me know if we are deciding on disabling any of the mentioned feature or users can be just allowed to operate on public lists as they want, which should not affect the main data i guess

Users are not able to *rename* or *delete* public lists, (so you are right that we need to disable these) but they can perform operations that end up creating a new list based on a public list. This can mean *duplicate*, as well as the set operations like *Intersect*, *Combine*, etc.

**Comment by heralden** [comment]
Resolved with #560
