### ISSUE TITLE
My Data - list operation buttons should match the names in the JSP UI

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#463]
The list operation buttons, (especially the set operation buttons) difference buttons should say the same labels as the JSP UI  e.g. the duplicate button should say "copy". This will make it easier for people to migrate from the old UI to the new

**Comment by evans407** [comment]
Hi @yochannah  I am an outreach applicant and i would love a chance to contribute to this project

**Comment by heralden** [comment]
Please go ahead @evans407. You can find the names of the old buttons here: https://www.flymine.org/flymine/bag.do?subtab=view
