### ISSUE TITLE
My Data: the list type section should handle long type names

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#464]
"gene" and "protein" are rather short, but it's possible to make lists out of any data type. We should make sure that long list type names are handled gracefully - either stretch the box to cover the whole type or truncate it neatly. right now it overflows its box. 

Example from yeastmine: 

<img width="1111" alt="screenshot of the bug described above" src="https://user-images.githubusercontent.com/9271438/72192939-57e95880-33bc-11ea-8c11-c6915548f6b9.png">

**Comment by ayushi1998** [comment]
I would like to take this up?

**Comment by heralden** [comment]
@ayushi1998 Please go ahead! You can find this example at the bottom of this page.
http://bluegenes.apps.intermine.org/yeastmine/mymine
