### ISSUE TITLE
"Show me an example" buttons are inconsistent between pages

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#465]
On the region search [show me an example] is up on the top, in the list upload page there is an EXAMPLE button on the bottom of the page. We should pick one location and be consistent about it, so that users can consistently find it!

**Comment by itolimaesther** [comment]
Hi, I'm an outreachy applicant for May 2020. Please I will love to contribute to this issue.

**Comment by heralden** [comment]
Go ahead, I have assigned you to the issue.

**Comment by itolimaesther** [comment]
Alright Thanks
