### ISSUE TITLE
Make it easier to move multiple lists into a folder

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#469]
https://github.com/intermine/bluegenes/pull/444 makes it easy to create folders, but if you have a lot of lists, dragging a list from the bottom all the way to a folder on the top could be a lot of work.

It would be useful to offer more ways of moving one or more lists into a folder.
- A new button in *My Data* which lets you move all selected lists into a folder (the modal would let you choose one from a list of all your folders)
- Support selecting (toggling) one or more lists in the organize modal, then select a target folder and all those lists will be moved into that folder without drag and dropping

**Comment by heralden** [comment]
Note that the second solution would allow the organize modal to also be useable on touch devices, with little to no extra work.

**Comment by yochannah** [comment]
+1  I like option 2, too
