### ISSUE TITLE
Generate API key in profile page

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#472]
I guess this is another thing we need in Bluegenes which the JSP has?
Seems like the profile page is the most suitable place to put it.

**Comment by ayushi1998** [comment]
Is this issue solved?

**Comment by heralden** [comment]
Hello @ayushi1998. No, it still needs to be done. It will require knowledge of ClojureScript (see https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/pages/profile/views.cljs) and use the `/user/tokens` endpoint (http://iodocs.apps.intermine.org/flymine/docs#/ws-perma-tokens/POST/user/tokens).

The end product should be similar to this.

![2020-03-11-113318_853x270_scrot](https://user-images.githubusercontent.com/3865590/76412794-2d038c80-638c-11ea-903b-a92d2b406fc4.png)


It's not very beginner friendly, but you are welcome to pick it up if you want.
