### ISSUE TITLE
Unable to change tabs for upload results 

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#479]
On the page `/upload/save`

**Comment by itolimaesther** [comment]
Hi, I'm an outreachy applicant for May 2020. Please I will love to contribute to this issue.

**Comment by heralden** [comment]
Assigned!

**Comment by itolimaesther** [comment]
@uosl Do you mind explaining more on the issue

**Comment by yochannah** [comment]
on the upload page, using the example, you should get a screen like this: 

![image](https://user-images.githubusercontent.com/9271438/76443929-16285e80-63bb-11ea-91a9-df2fa90afeb7.png)

the ambiguous, synonym, and matches tabs just flicker and don't change when clicked.
