### ISSUE TITLE
Templates: create dropdown for scenarios where there are only a few permitted values

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#48]
Screenshot of the functionality in the jsp UI:

![image](https://cloud.githubusercontent.com/assets/9271438/21849338/12832dd4-d7fd-11e6-9d09-e31a15407be3.png)

Is this information available via a webservice do we know? @joshkh @julie-sullivan

**Comment by yochannah** [comment]
See also #71 - same issue, different page

**Comment by yochannah** [comment]
Update - this is still an issue. Some organisms have dropdowns but not much else.

**Comment by yochannah** [comment]
update - yes this issue is still valid 🤦‍♂

**Comment by heralden** [comment]
Fixed now that permitted values are fetched for constraints.
