### ISSUE TITLE
Go to home page on successful login

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#485]
Otherwise you might be on a page with outdated/incorrect data for your user.

**Comment by noorfathima11** [comment]
Can I work on this?

**Comment by heralden** [comment]
Sure, go ahead! 👍

**Comment by komecodes** [comment]
Hello, Is this issue still open? I would like to work on it

**Comment by noorfathima11** [comment]
Have already raised a PR. https://github.com/intermine/bluegenes/pull/489
