### ISSUE TITLE
Make use of React error boundaries

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#486]
We should wrap the webapp in a component with the `component-did-catch` lifecycle defined, along with an appropriate "something went wrong" page.
This would be used if something goes wrong when rendering a page.

https://lilac.town/writing/modern-react-in-cljs-error-boundaries/
https://reactjs.org/docs/error-boundaries.html

I'm not aware of any present bug allowing you to break rendering of a page, but there's always one somewhere [=

**Comment by yochannah** [comment]
there have definitely been bugs like this in the past, so it's likely we'll end up with some in the future :) 
this is a brilliant idea!

**Comment by lape15** [comment]
Hi @uosl I am an outreach applicant and i would love a chance to contribute to this project

**Comment by heralden** [comment]
Hello @lape15, I have assigned the issue to you.

Note that this will require Clojure knowledge, specifically hiccup. Here's a good tutorial: https://medium.com/makimo-tech-blog/hiccup-lightning-tutorial-6494e477f3a5

Please let us know if you change your mind or have any updates.

**Comment by lape15** [comment]
Thank you
