### ISSUE TITLE
UI/UX Issue on Help Page

### ISSUE THREAD

**Issue by kirayan01** [intermine/bluegenes#501]
Hi, I am Kira, I am from Outreach. 
When I explore bulegenes demo, I found on Help Page, it will be more readable for users if there is more space add to the left side text. 

![Screen Shot 2020-04-01 at 8 50 02 PM](https://user-images.githubusercontent.com/45933354/78209348-a0fcf600-745b-11ea-8065-364d5c51536c.png)

**Comment by heralden** [comment]
Hello Kira.

Thanks for the suggestion. We probably should redesign that page or maybe even remove it altogether and move any necessary information to the footer.

Wireframe/sketches/designs are welcome!

**Comment by kirayan01** [comment]
> Hello Kira.
> 
> Thanks for the suggestion. We probably should redesign that page or maybe even remove it altogether and move any necessary information to the footer.
> 
> Wireframe/sketches/designs are welcome!

Hi Herald,
Thank you for your reply! Yeah, I am thinking if the website design. I will write my proposal for my final project application on Outreach. 

Cheers,
Kira
My personal website: https://kirayan01.github.io/kirayan/
