### ISSUE TITLE
Handle conflicts from list upgrading

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#512]
The response from the list endpoint should include data on outdated lists, which we'll need to display a button for upgrading beside it on the MyData page. We should be able to reuse the ID resolver used when uploading data to handle migrating and fixing conflicts.

**Comment by heralden** [comment]
We will also need to display the other statuses in the UI (eg. up-to-date, updating, manual upgrade required).

**Comment by danielabutano** [comment]
@uosl I put here two links might be useful

- [MyMine/List page](https://flymine.readthedocs.io/en/latest/mymine/DocumentationMyMine.html#lists)
- and the [resolution page](https://flymine.readthedocs.io/en/latest/lists/upload/Documentationlistupload.html#listconfirmationpage)

**Comment by danielabutano** [comment]
When intermine server is upgrading the list, MyData page should show the correct number of items contained in the list, or 0 if the list has not been updated yet.
At the moment it always shows 0. You need to logout and login to refresh these values
