### ISSUE TITLE
Credits info for funders

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#531]
Have a region that shows:

1) Who funds intermine (generally. e.g. wellcome, bbsrc, nih)
2) Who maintains a given intermine and then who funds the maintainers

**Comment by yochannah** [comment]
will need to come from intermine properties somewhere

**Comment by yochannah** [comment]
See #530 as well, maybe same or related page

**Comment by heralden** [comment]
After further discussion, we'll give a try at having this information at the bottom of the new front page design.
