### ISSUE TITLE
QB: Crash when expanding Data Source in Chickpeamine

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#551]
Data Source under Data Set. It doesn't seem like this class exists in the model, so perhaps it shouldn't be present in the querybuilder?

This also causes the *Browse data sources* button on the front page to not return results, as Data Set is part of that query.

**Comment by sammyjava** [comment]
That's a bug -- all DataSets should have a populated DataSource reference. I've got a whole new set of beany mines with new data models and always with DataSource->DataSets populated coming up soon, so I'd just close this as a "next relase" bug fix. Thanks for catching it, though!

**Comment by heralden** [comment]
Thanks for letting us know!

I still think Bluegenes should handle this better, by showing an error message when it's unable to find the class in the model instead of crashing, so I'll work on implementing that.

**Comment by sammyjava** [comment]
Agreed. The class is in the model, but it has 0 instances. So that's a bit different from it not being in the model.

**Comment by heralden** [comment]
Closing this as it seems like it's fixed on Chickpeamine, and a while back I fixed Bluegenes' handling of classes with 0 instances.
