### ISSUE TITLE
Replace readthedocs and wordpress links with intermine.org

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#558]
These are linked to from the footer and other places (do a grep).

They are fragmented right now, and it makes sense to collect them all on the intermine homepage.

Depends on this issue being completed.
https://github.com/intermine/intermine-homepage-2017/issues/67

**Comment by iambami** [comment]
Hi
Is this issue still open?

**Comment by heralden** [comment]
Hello! Sorry for the late response. It is still open, but dependent on updating the Intermine homepage (see link above) which will be a bit difficult for outside contributors.
Thank you for showing interest.
