### ISSUE TITLE
Update placeholder in region search textarea

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#565]
It says *Type chromosome coords here, or click [Show me an example] above.* when the example button has been moved from above to below, and is now labeled **Show example** instead. We should update the placeholder text!

You can see the issue on the region search page: http://bluegenes.apps.intermine.org/default/regions

**Comment by snehal199** [comment]
Hey @uosl, can I work on this?

**Comment by heralden** [comment]
Sure @snehal199, I have assigned you. Please let me know if you have any questions.

**Comment by snehal199** [comment]
I plan to change the [views.cljs](https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/pages/regions/views.cljs) file as of now. Looks like that would resolve the issue.Should I go ahead with this?

**Comment by heralden** [comment]
Yes, that looks like the right place to make the change. Go ahead!
