### ISSUE TITLE
Enrichment: don't say we've selected an enrichment column if there are no columns suitable for enrichment.

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#58]
![image](https://cloud.githubusercontent.com/assets/9271438/21991107/3bb1b3dc-dc09-11e6-9ee1-b1c54d9c4afe.png)

as you can see in this image, there are no enrichment widgets available for the types displayed in the current results page, but the top left bit likes to pretend its enriching genes anyway. Wrong! Sad.

**Comment by joshkh** [comment]
Appears to be fixed!
