### ISSUE TITLE
Home Page feedback

### ISSUE THREAD

**Issue by danielabutano** [intermine/bluegenes#621]
- Horizontal line shown only after the Go by Most Popular Queries section. I would remove it or add as separator after every section
- External Tool section.I would remove it. I think is more appropriate to add this section on the intermine.org website, next to the intermine-cross-search-tool
- Consistent use of low/upper case on section titles. E.g. INTERMINE FOR ALL -> InterMine for All and menu (why login has capital letters?)
- Funding section: I would reduce the size and maybe change the background color?
- In the features/CTA section, replace headers by button as they're redundant *(suggested by Sergio)*
- Space between boxes. I would reduce the space (vertical spece) between the sections _Analyse your lists_, _Browse data sources_, _Build your own query_..... 
- I would list the menu 
![image](https://user-images.githubusercontent.com/1678179/107623993-1deb2580-6c52-11eb-94b6-2ea9ae20c8f2.png)
in the same order of the current one
![image](https://user-images.githubusercontent.com/1678179/107624105-4a06a680-6c52-11eb-99b0-2525d53a63c9.png)
- Feedback form: I would hide the form and add a link somewhere

**Comment by sergiocontrino** [comment]
- templates: is it the right name?  should it be linked to 'most popular queries' (e.g. 'queries', 'prepared queries', 'popular q'..)?
- upload: could also this be linked to the button below (e.g. analyse)?
- regions: i think the regions search would deserve a space in the page (e.g. a text box with the search example defaulting to all features, even just below the text search)
- replacing headers with the relevant button (see previous comment):
   - proposed text: analyse data, browse sources, build your own query, tutorials, what's new, web services
   - i would remove the first phrase from the byoq section (Build your own data search using the Query Builder. )
   - tutorial: contact us as a link to the submit form
   - what's new: button becomes link to 'more' or 'all posts'
   - what's new: we could also think about switching to twitter feed in case (unrelated to this ticket)
-   intermine for all: i think a 'phylogenetic' graph would be nicer. don't particularly like the box board. 
    - can the icon size be limited (see covidmine and fawnmine)
    - covidmine does not appear in 'other mines' filter
- external tool: as discussed i would give it less prominence (a navigation bar?)

**Comment by heralden** [comment]
Closing this as we discussed all these points and I'll be creating issues for the changes we decided to go for.
