### ISSUE TITLE
Improve Cite us button/link

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#663]
Cite us/mine in footer should link to http://intermine.org/publications/ with query param or something which causes the correct publication to show obviously at the top (other mines should be able to override this link with their own in web-properties).

*Update: The same functionality should be given to the CITE US call-to-action button on the home page.*

**Comment by heralden** [comment]
This feature has been added to intermine.org in https://github.com/intermine/intermine-homepage-2017/pull/73

The two CITE US buttons use web property `project.citation`, so it should be a simple matter of changing that for Humanmine and Flymine. We could alternatively use a different, new web property to avoid affecting the JSP webapp.

Humanmine: http://intermine.org/publications/?doi=10.1093/bioinformatics/bts577
Flymine: http://intermine.org/publications/?doi=10.1186/gb-2007-8-7-r129

**Comment by meenal06** [comment]
Hi @uosl , can I work on this issue?

**Comment by heralden** [comment]
@meenal06 Sorry! This can only be fixed internally on our servers. Thank you for your interest.

**Comment by meenal06** [comment]
Sure, no worries!

**Comment by sergiocontrino** [comment]
hi @uosl , i think the url should be this 
http://doi.org/10.1186/gb-2007-8-7-r129
not the one you mention in the comment. if this is wrong, please let me know.

**Comment by sergiocontrino** [comment]
- added to humanmine
`project.citation=<a href="http://intermine.org/publications/?doi=10.1186/gb-2007-8-7-r129" target="_blank">Smith RN, et al. InterMine: a flexible data warehouse system for the integration and analysis of heterogeneous biological data. Bioinformatics 2012; Vol28, Issue 23.</a`
- modified in flymine
`-project.citation=<a href="https://www.ncbi.nlm.nih.gov/pubmed/17615057" target="_blank">Lyne R, et al. FlyMine: an integrated database for Drosophila and Anopheles genomics. Genome Biol. 2007;8(7):R129.</a>
+project.citation=<a href="http://intermine.org/publications/?doi=10.1186/gb-2007-8-7-r129" target="_blank">Lyne R, et al. FlyMine: an integrated database for Drosophila and Anopheles genomics. Genome Biol. 2007;8(7):R129.</a>
`
please let me know if only url needed.

**Comment by heralden** [comment]
@sergiocontrino Bluegenes will extract the URL from the href, so that works fine.

Is http://intermine.org/publications/?doi=10.1186/gb-2007-8-7-r129 correct for Humanmine though? Shouldn't it link to http://intermine.org/publications/?doi=10.1093/bioinformatics/bts577 ?

**Comment by sergiocontrino** [comment]
thank you @uosl , corrected

`-project.citation=<a href="http://intermine.org/publications/?doi=10.1186/gb-2007-8-7-r129" target="_blank">Smith RN, et al. InterMine: a flexible data warehouse system for the integration and analysis of heterogeneous biological data. Bioinformatics 2012; Vol28, Issue 23.</a>
+project.citation=<a href="http://intermine.org/publications/?doi=10.1093/bioinformatics/bts577" target="_blank">Smith RN, et al. InterMine: a flexible data warehouse system for the integration and analysis of heterogeneous biological data. Bioinformatics 2012; Vol28, Issue 23.</a>
`

**Comment by heralden** [comment]
Thanks!
