### ISSUE TITLE
Templates have disappeared from the report page

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#67]
looks like it uses redgenes.components.table and is failing silently. 
Convert to an im table?

**Comment by yochannah** [comment]
The templates used to be in that red box down there.... (border added for visual effect, it's not really on the report page)

![image](https://cloud.githubusercontent.com/assets/9271438/22557562/c7efc1ac-e962-11e6-99d7-b253d699cd82.png)

**Comment by yochannah** [comment]
#60, #67, #57, #59, #46, #43, #45, and maybe #57 and #10, are all report related issues .

**Comment by yochannah** [comment]
After a quick chat with @joshkh - this was working under js imtables, so probably just needs to be replaced with imtables 3 / cljs imtables. Josh says he'll take a look....

**Comment by yochannah** [comment]
see #46 and #59 when addressing this.

**Comment by joshkh** [comment]
@yochannah Can you confirm that it's now working? On the dev branch I see Templates, Collections, and References.

By the way I really like what you've done with the CSS for the im-table buttons!

**Comment by yochannah** [comment]
Yep. Nice'un!
