### ISSUE TITLE
Run tests in headless mode for CI

### ISSUE THREAD

**Issue by meenal06** [intermine/bluegenes#706]
Currently tests are being run in interactive mode rather than headless as headless mode hides the browser and provide better visibility throughout the logs rather than the interactive mode.

**Comment by heralden** [comment]
Just to confirm, does headless mode still create artifacts?

Here's an example of the artifacts automaticaly uploaded to CircleCI.
```
    cypress/videos/pr_test.js.mp4
    cypress/videos/user_account/login_logout_user.spec.js.mp4
    cypress/videos/user_account/register_user.spec.js.mp4
    cypress/screenshots/user_account/login_logout_user.spec.js/cypressintegrationuser_accountlogin_logout_user.spec.js -- it should logout user successfully (failed).png
```

**Comment by meenal06** [comment]
Yes, it creates the artifacts!
