### ISSUE TITLE
Query Builder: make constraints easier to specify where dropdown / typeahead is possible

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#71]
Feedback from Gos: Constraining in the QB by organism is almost impossible when you aren't quite sure what to put in a given field - for example, should it be "D. melanogaster", "Drosophila melanogaster", something else? 

Where possible options are less than some small n (20? 30?), we should provide a way to make it easier to select a correct option. Gos suggested a dropdown or typeahead. 

The possible values web service may be handy here. http://iodocs.apps.intermine.org/flymine/docs#/ws-possible-values/GET/path/values

**Comment by yochannah** [comment]
+1 from rachel: 
>Needs drop-downs and type-aheads for the constraints.  (+ null values and loop queries).

**Comment by joshkh** [comment]
Null values / outer joins are on the roadmap!

Typeahead was introduced in https://github.com/intermine/redgenes/pull/100

Paths with less than or equal to 100 values show all values in a dropdown. Any values that contain part of the value in the constraint bubble to the top.

Paths with more than 100 and less than 7000 values have a typeahead behaviour that require a user to enter three or more characters into the constraint before filtering.

Paths with more than 7000 values have no typeahead.

While /service/values is useful there's no way to limit the results, so asking for Gene.symbol will return all 500k+ which takes a while! To get around this I added a `unique-values` function to imcljs that first counts the query using a summaryPath and limits the results to 1. It still returns the unique value count which I can use to run a second query if it's below a limit:

https://github.com/intermine/imcljs/blob/master/src/imcljs/fetch.cljs#L35

I'm going to close this ticket and create a new one for outer joins.
