### ISSUE TITLE
Query Builder: Improve lookup for constraints:

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#74]
Feedback from Rachel: 

* Constrain gene: it’s not clear that you need to change this to a LOOKUP.
* I think the LOOKUP constraint is case sensitive, which it isn’t in current intermine.

**Comment by joshkh** [comment]
1. Constraints on classes such as Gene default to LOOKUP. (check devredgenes.apps.intermine.org, this might have been fixed after you tested)

2. `Lookup`, `In some list`, `Not in some list`, etc. get translated to their actual values `LOOKUP`, `IN`, `NOT IN`, etc. The goal was to provide people with a more human friendly values. 

No action taken unless I'm misunderstanding your feedback, @rachellyne
