### ISSUE TITLE
Create server side cache clear route

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#85]
**Why?** because having an old version of the client side scripts can make the app just appear broken. In order to ensure that users have a good experience we *must* manage browser caching as efficiently as possibly and make sure to expire old client side scripts effectively.

Something like redgenes.whatever.com/clearcache could be captured by the minimal existing ring server to force the browser to download a new copy of the client side application. We'd need to make sure to pass this to the client side too to ensure that the localstorage is expired as well.

**Comment by heralden** [comment]
Not sure if this is still a problem, as I see we add the version to the bundle `app.js?v=0.9.9-SNAPSHOT`and if this isn't enough, `lein-cljsbuild` supports generating a cache-busting hash like `app.3jf91fs4f.js`, which will definitely force the browser to download the newest client script.

For localstorage, it's handled in `events/boot.cljs` and we can improve upon it there.

I'll come back to this once I've tested how well the current solution works in expiring old scripts.

**Comment by yochannah** [comment]
I suspect the cache clearer `app.js?v=0.9.9-SNAPSHOT` method doesn't actually work in prod but might in dev.

**Comment by heralden** [comment]
Fixed with https://github.com/intermine/bluegenes/pull/435 using cache-busting hash feature of ClojureScript compiler.
