### ISSUE TITLE
Report page: homologue links should use the portal

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes#87]
from @julie-sullivan 

I am probably reading this wrong but if you are going to link out to mines you should use the portal.

http://devredgenes.apps.intermine.org/##/reportpage/flymine-beta/Gene/1072158

e.g. Cdk8 links out to

        http://beta.flymine.org/beta/report.do?id=1016625

Should link out to this instead:

http://beta.flymine.org/beta/portal.do?class=Gene&externalids=FBgn0015618

Or if you want to use the symbol in the URL, just add the organism too.

http://beta.flymine.org/beta/portal.do?class=Gene&externalids=Cdk8&extraValue=D.+melanogaster

Ignore me if you are using the portal!

**Comment by julie-sullivan** [comment]
Docs http://intermine.readthedocs.io/en/latest/webapp/linking-in/

**Comment by yochannah** [comment]
Here's the offending line of code: https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/sections/reportpage/components/minelinks.cljs#L36

**Comment by yochannah** [comment]
Homologues will be migrated to the homology tool
